const rawDataA1 = [
  // --- LEVEL A1 (The Basics) ---
  {w:"Abend",a:"der",l:"A1",t:{en:"evening",uk:"вечір"}},
  {w:"Adresse",a:"die",l:"A1",t:{en:"address",uk:"адреса"}},
  {w:"Alter",a:"das",l:"A1",t:{en:"age",uk:"вік"}},
  {w:"Antwort",a:"die",l:"A1",t:{en:"answer",uk:"відповідь"}},
  {w:"Apfel",a:"der",l:"A1",t:{en:"apple",uk:"яблуко"}},
  {w:"Apotheke",a:"die",l:"A1",t:{en:"pharmacy",uk:"аптека"}},
  {w:"Arbeit",a:"die",l:"A1",t:{en:"work",uk:"робота"}},
  {w:"Arzt",a:"der",l:"A1",t:{en:"doctor",uk:"лікар"}},
  {w:"Auge",a:"das",l:"A1",t:{en:"eye",uk:"око"}},
  {w:"August",a:"der",l:"A1",t:{en:"August",uk:"серпень"}},
  {w:"Ausbildung",a:"die",l:"A1",t:{en:"education",uk:"освіта"}},
  {w:"Ausflug",a:"der",l:"A1",t:{en:"excursion",uk:"екскурсія"}},
  {w:"Ausgang",a:"der",l:"A1",t:{en:"exit",uk:"вихід"}},
  {w:"Auto",a:"das",l:"A1",t:{en:"car",uk:"автомобіль"}},
  {w:"Baby",a:"das",l:"A1",t:{en:"baby",uk:"дитина"}},
  {w:"Bäckerei",a:"die",l:"A1",t:{en:"bakery",uk:"пекарня"}},
  {w:"Bad",a:"das",l:"A1",t:{en:"bath",uk:"ванна"}},
  {w:"Bahnhof",a:"der",l:"A1",t:{en:"train station",uk:"вокзал"}},
  {w:"Bahnsteig",a:"der",l:"A1",t:{en:"platform",uk:"перон"}},
  {w:"Balkon",a:"der",l:"A1",t:{en:"balcony",uk:"балкон"}},
  {w:"Banane",a:"die",l:"A1",t:{en:"banana",uk:"банан"}},
  {w:"Bauch",a:"der",l:"A1",t:{en:"stomach",uk:"живіт"}},
  {w:"Baum",a:"der",l:"A1",t:{en:"tree",uk:"дерево"}},
  {w:"Bein",a:"das",l:"A1",t:{en:"leg",uk:"нога"}},
  {w:"Beispiel",a:"das",l:"A1",t:{en:"example",uk:"приклад"}},
  {w:"Beruf",a:"der",l:"A1",t:{en:"profession",uk:"професія"}},
  {w:"Bett",a:"das",l:"A1",t:{en:"bed",uk:"ліжко"}},
  {w:"Bier",a:"das",l:"A1",t:{en:"beer",uk:"пиво"}},
  {w:"Bild",a:"das",l:"A1",t:{en:"picture",uk:"картина"}},
  {w:"Bildschirm",a:"der",l:"A1",t:{en:"screen",uk:"екран"}},
  {w:"Birne",a:"die",l:"A1",t:{en:"pear",uk:"груша"}},
  {w:"Bitte",a:"die",l:"A1",t:{en:"request",uk:"прохання"}},
  {w:"Blatt",a:"das",l:"A1",t:{en:"leaf",uk:"листок"}},
  {w:"Bleistift",a:"der",l:"A1",t:{en:"pencil",uk:"олівець"}},
  {w:"Blume",a:"die",l:"A1",t:{en:"flower",uk:"квітка"}},
  {w:"Bluse",a:"die",l:"A1",t:{en:"blouse",uk:"блузка"}},
  {w:"Boden",a:"der",l:"A1",t:{en:"floor",uk:"підлога"}},
  {w:"Brief",a:"der",l:"A1",t:{en:"letter",uk:"лист"}},
  {w:"Brot",a:"das",l:"A1",t:{en:"bread",uk:"хліб"}},
  {w:"Brötchen",a:"das",l:"A1",t:{en:"bread roll",uk:"булочка"}},
  {w:"Bruder",a:"der",l:"A1",t:{en:"brother",uk:"брат"}},
  {w:"Buch",a:"das",l:"A1",t:{en:"book",uk:"книга"}},
  {w:"Buchstabe",a:"der",l:"A1",t:{en:"letter",uk:"літера"}},
  {w:"Bus",a:"der",l:"A1",t:{en:"bus",uk:"автобус"}},
  {w:"Butter",a:"die",l:"A1",t:{en:"butter",uk:"масло"}},
  {w:"Café",a:"das",l:"A1",t:{en:"cafe",uk:"кафе"}},
  {w:"Chance",a:"die",l:"A1",t:{en:"chance",uk:"шанс"}},
  {w:"Chef",a:"der",l:"A1",t:{en:"boss",uk:"шеф"}},
  {w:"Computer",a:"der",l:"A1",t:{en:"computer",uk:"комп'ютер"}},
  {w:"Dank",a:"der",l:"A1",t:{en:"thanks",uk:"подяка"}},
  {w:"Datum",a:"das",l:"A1",t:{en:"date",uk:"дата"}},
  {w:"Dienstag",a:"der",l:"A1",t:{en:"Tuesday",uk:"вівторок"}},
  {w:"Ding",a:"das",l:"A1",t:{en:"thing",uk:"річ"}},
  {w:"Donnerstag",a:"der",l:"A1",t:{en:"Thursday",uk:"четвер"}},
  {w:"Dorf",a:"das",l:"A1",t:{en:"village",uk:"село"}},
  {w:"Drucker",a:"der",l:"A1",t:{en:"printer",uk:"принтер"}},
  {w:"Durst",a:"der",l:"A1",t:{en:"thirst",uk:"спрага"}},
  {w:"Ei",a:"das",l:"A1",t:{en:"egg",uk:"яйце"}},
  {w:"Eingang",a:"der",l:"A1",t:{en:"entrance",uk:"вхід"}},
  {w:"Einladung",a:"die",l:"A1",t:{en:"invitation",uk:"запрошення"}},
  {w:"Eis",a:"das",l:"A1",t:{en:"ice",uk:"лід/морозиво"}},
  {w:"Eltern",a:"die",l:"A1",t:{en:"parents",uk:"батьки"}},
  {w:"Ende",a:"das",l:"A1",t:{en:"end",uk:"кінець"}},
  {w:"Entschuldigung",a:"die",l:"A1",t:{en:"excuse",uk:"вибачення"}},
  {w:"Essen",a:"das",l:"A1",t:{en:"food",uk:"їжа"}},
  {w:"Euro",a:"der",l:"A1",t:{en:"euro",uk:"євро"}},
  {w:"Fahrrad",a:"das",l:"A1",t:{en:"bicycle",uk:"велосипед"}},
  {w:"Familie",a:"die",l:"A1",t:{en:"family",uk:"сім'я"}},
  {w:"Farbe",a:"die",l:"A1",t:{en:"color",uk:"колір"}},
  {w:"Februar",a:"der",l:"A1",t:{en:"February",uk:"лютий"}},
  {w:"Fehler",a:"der",l:"A1",t:{en:"mistake",uk:"помилка"}},
  {w:"Fenster",a:"das",l:"A1",t:{en:"window",uk:"вікно"}},
  {w:"Ferien",a:"die",l:"A1",t:{en:"vacation",uk:"канікули"}},
  {w:"Fernseher",a:"der",l:"A1",t:{en:"TV",uk:"телевізор"}},
  {w:"Fest",a:"das",l:"A1",t:{en:"festival",uk:"свято"}},
  {w:"Feuer",a:"das",l:"A1",t:{en:"fire",uk:"вогонь"}},
  {w:"Fieber",a:"das",l:"A1",t:{en:"fever",uk:"температура"}},
  {w:"Film",a:"der",l:"A1",t:{en:"movie",uk:"фільм"}},
  {w:"Finger",a:"der",l:"A1",t:{en:"finger",uk:"палець"}},
  {w:"Fisch",a:"der",l:"A1",t:{en:"fish",uk:"риба"}},
  {w:"Flasche",a:"die",l:"A1",t:{en:"bottle",uk:"пляшка"}},
  {w:"Fleisch",a:"das",l:"A1",t:{en:"meat",uk:"м'ясо"}},
  {w:"Flughafen",a:"der",l:"A1",t:{en:"airport",uk:"аеропорт"}},
  {w:"Flugzeug",a:"das",l:"A1",t:{en:"airplane",uk:"літак"}},
  {w:"Flur",a:"der",l:"A1",t:{en:"hallway",uk:"коридор"}},
  {w:"Formular",a:"das",l:"A1",t:{en:"form",uk:"формуляр"}},
  {w:"Foto",a:"das",l:"A1",t:{en:"photo",uk:"фотографія"}},
  {w:"Frage",a:"die",l:"A1",t:{en:"question",uk:"питання"}},
  {w:"Frau",a:"die",l:"A1",t:{en:"woman",uk:"жінка"}},
  {w:"Freitag",a:"der",l:"A1",t:{en:"Friday",uk:"п'ятниця"}},
  {w:"Freizeit",a:"die",l:"A1",t:{en:"free time",uk:"дозвілля"}},
  {w:"Freund",a:"der",l:"A1",t:{en:"friend",uk:"друг"}},
  {w:"Frühstück",a:"das",l:"A1",t:{en:"breakfast",uk:"сніданок"}},
  {w:"Fuß",a:"der",l:"A1",t:{en:"foot",uk:"стопа"}},
  {w:"Fußball",a:"der",l:"A1",t:{en:"football",uk:"футбол"}},
  {w:"Gabel",a:"die",l:"A1",t:{en:"fork",uk:"виделка"}},
  {w:"Garage",a:"die",l:"A1",t:{en:"garage",uk:"гараж"}},
  {w:"Garten",a:"der",l:"A1",t:{en:"garden",uk:"сад"}},
  {w:"Gast",a:"der",l:"A1",t:{en:"guest",uk:"гість"}},
  {w:"Gebühr",a:"die",l:"A1",t:{en:"fee",uk:"збір"}},
  {w:"Geld",a:"das",l:"A1",t:{en:"money",uk:"гроші"}},
  {w:"Gemüse",a:"das",l:"A1",t:{en:"vegetables",uk:"овочі"}},
  {w:"Gepäck",a:"das",l:"A1",t:{en:"luggage",uk:"багаж"}},
  {w:"Gericht",a:"das",l:"A1",t:{en:"dish",uk:"страва"}},
  {w:"Geschenk",a:"das",l:"A1",t:{en:"gift",uk:"подарунок"}},
  {w:"Geschirr",a:"das",l:"A1",t:{en:"dishes",uk:"посуд"}},
  {w:"Gesicht",a:"das",l:"A1",t:{en:"face",uk:"обличчя"}},
  {w:"Getränk",a:"das",l:"A1",t:{en:"drink",uk:"напій"}},
  {w:"Glas",a:"das",l:"A1",t:{en:"glass",uk:"склянка"}},
  {w:"Gleis",a:"das",l:"A1",t:{en:"track",uk:"колія"}},
  {w:"Glück",a:"das",l:"A1",t:{en:"luck",uk:"щастя"}},
  {w:"Gott",a:"der",l:"A1",t:{en:"god",uk:"бог"}},
  {w:"Grad",a:"der",l:"A1",t:{en:"degree",uk:"градус"}},
  {w:"Gramm",a:"das",l:"A1",t:{en:"gram",uk:"грам"}},
  {w:"Größe",a:"die",l:"A1",t:{en:"size",uk:"розмір"}},
  {w:"Gruppe",a:"die",l:"A1",t:{en:"group",uk:"група"}},
  {w:"Gruß",a:"der",l:"A1",t:{en:"greeting",uk:"привіт"}},
  {w:"Haar",a:"das",l:"A1",t:{en:"hair",uk:"волосся"}},
  {w:"Hals",a:"der",l:"A1",t:{en:"neck",uk:"шия/горло"}},
  {w:"Haltestelle",a:"die",l:"A1",t:{en:"stop",uk:"зупинка"}},
  {w:"Hand",a:"die",l:"A1",t:{en:"hand",uk:"рука"}},
  {w:"Handy",a:"das",l:"A1",t:{en:"mobile phone",uk:"мобільний телефон"}},
  {w:"Haus",a:"das",l:"A1",t:{en:"house",uk:"будинок"}},
  {w:"Heimat",a:"die",l:"A1",t:{en:"homeland",uk:"батьківщина"}},
  {w:"Heizung", a:"die", l:"A1", t:{en:"heating", uk:"опалення"}},
  {w:"Hemd", a:"das", l:"A1", t:{en:"shirt", uk:"сорочка"}},
  {w:"Herr", a:"der", l:"A1", t:{en:"gentleman", uk:"пан"}},
  {w:"Hilfe", a:"die", l:"A1", t:{en:"help", uk:"допомога"}},
  {w:"Hobby", a:"das", l:"A1", t:{en:"hobby", uk:"хобі"}},
  {w:"Hotel", a:"das", l:"A1", t:{en:"hotel", uk:"готель"}},
  {w:"Hund", a:"der", l:"A1", t:{en:"dog", uk:"собака"}},
  {w:"Hunger", a:"der", l:"A1", t:{en:"hunger", uk:"голод"}},
  {w:"Idee", a:"die", l:"A1", t:{en:"idea", uk:"ідея"}},
  {w:"Inhalt", a:"der", l:"A1", t:{en:"content", uk:"зміст"}},
  {w:"Insel", a:"die", l:"A1", t:{en:"island", uk:"острів"}},
  {w:"Internet", a:"das", l:"A1", t:{en:"internet", uk:"інтернет"}},
  {w:"Jacke", a:"die", l:"A1", t:{en:"jacket", uk:"куртка"}},
  {w:"Jahr", a:"das", l:"A1", t:{en:"year", uk:"рік"}},
  {w:"Januar", a:"der", l:"A1", t:{en:"January", uk:"січень"}},
  {w:"Job", a:"der", l:"A1", t:{en:"job", uk:"робота"}},
  {w:"Junge", a:"der", l:"A1", t:{en:"boy", uk:"хлопець"}},
  {w:"Kaffee", a:"der", l:"A1", t:{en:"coffee", uk:"кава"}},
  {w:"Kalender", a:"der", l:"A1", t:{en:"calendar", uk:"календар"}},
  {w:"Kamera", a:"die", l:"A1", t:{en:"camera", uk:"камера"}},
  {w:"Karte", a:"die", l:"A1", t:{en:"card/map", uk:"картка/карта"}},
  {w:"Kartoffel", a:"die", l:"A1", t:{en:"potato", uk:"картопля"}},
  {w:"Käse", a:"der", l:"A1", t:{en:"cheese", uk:"сир"}},
  {w:"Kasse", a:"die", l:"A1", t:{en:"cash register", uk:"каса"}},
  {w:"Katze", a:"die", l:"A1", t:{en:"cat", uk:"кішка"}},
  {w:"Keller", a:"der", l:"A1", t:{en:"cellar", uk:"підвал"}},
  {w:"Kette", a:"die", l:"A1", t:{en:"chain", uk:"ланцюжок"}},
  {w:"Kind", a:"das", l:"A1", t:{en:"child", uk:"дитина"}},
  {w:"Kino", a:"das", l:"A1", t:{en:"cinema", uk:"кінотеатр"}},
  {w:"Kiosk", a:"der", l:"A1", t:{en:"kiosk", uk:"кіоск"}},
  {w:"Kirche", a:"die", l:"A1", t:{en:"church", uk:"церква"}},
  {w:"Klasse", a:"die", l:"A1", t:{en:"class", uk:"клас"}},
  {w:"Kleid", a:"das", l:"A1", t:{en:"dress", uk:"сукня"}},
  {w:"Kleidung", a:"die", l:"A1", t:{en:"clothing", uk:"одяг"}},
  {w:"Koffer", a:"der", l:"A1", t:{en:"suitcase", uk:"валіза"}},
  {w:"Kollege", a:"der", l:"A1", t:{en:"colleague", uk:"колега"}},
  {w:"Kontakt", a:"der", l:"A1", t:{en:"contact", uk:"контакт"}},
  {w:"Konto", a:"das", l:"A1", t:{en:"account", uk:"рахунок"}},
  {w:"Kopf", a:"der", l:"A1", t:{en:"head", uk:"голова"}},
  {w:"Körper", a:"der", l:"A1", t:{en:"body", uk:"тіло"}},
  {w:"Kosten", a:"die", l:"A1", t:{en:"costs", uk:"витрати"}},
  {w:"Küche", a:"die", l:"A1", t:{en:"kitchen", uk:"кухня"}},
  {w:"Kuchen", a:"der", l:"A1", t:{en:"cake", uk:"пиріг"}},
  {w:"Kühlschrank", a:"der", l:"A1", t:{en:"fridge", uk:"холодильник"}},
  {w:"Kultur", a:"die", l:"A1", t:{en:"culture", uk:"культура"}},
  {w:"Kunde", a:"der", l:"A1", t:{en:"customer", uk:"клієнт"}},
  {w:"Kurs", a:"der", l:"A1", t:{en:"course", uk:"курс"}},
  {w:"Laden", a:"der", l:"A1", t:{en:"shop", uk:"магазин"}},
  {w:"Lampe", a:"die", l:"A1", t:{en:"lamp", uk:"лампа"}},
  {w:"Land", a:"das", l:"A1", t:{en:"country", uk:"країна"}},
  {w:"Laptop", a:"der", l:"A1", t:{en:"laptop", uk:"ноутбук"}},
  {w:"Leben", a:"das", l:"A1", t:{en:"life", uk:"життя"}},
  {w:"Lehrer", a:"der", l:"A1", t:{en:"teacher", uk:"вчитель"}},
  {w:"Leute", a:"die", l:"A1", t:{en:"people", uk:"люди"}},
  {w:"Licht", a:"das", l:"A1", t:{en:"light", uk:"світло"}},
  {w:"Lied", a:"das", l:"A1", t:{en:"song", uk:"пісня"}},
  {w:"Liter", a:"der", l:"A1", t:{en:"liter", uk:"літр"}},
  {w:"Löffel", a:"der", l:"A1", t:{en:"spoon", uk:"ложка"}},
  {w:"Luft", a:"die", l:"A1", t:{en:"air", uk:"повітря"}},
  {w:"Lust", a:"die", l:"A1", t:{en:"pleasure", uk:"бажання"}},
  {w:"Mädchen", a:"das", l:"A1", t:{en:"girl", uk:"дівчинка"}},
  {w:"Magen", a:"der", l:"A1", t:{en:"stomach", uk:"шлунок"}},
  {w:"Mai", a:"der", l:"A1", t:{en:"May", uk:"травень"}},
  {w:"Mal", a:"das", l:"A1", t:{en:"time/occurrence", uk:"раз"}},
  {w:"Mann", a:"der", l:"A1", t:{en:"man", uk:"чоловік"}},
  {w:"Mantel", a:"der", l:"A1", t:{en:"coat", uk:"пальто"}},
  {w:"Markt", a:"der", l:"A1", t:{en:"market", uk:"ринок"}},
  {w:"März", a:"der", l:"A1", t:{en:"March", uk:"березень"}},
  {w:"Maschine", a:"die", l:"A1", t:{en:"machine", uk:"машина"}},
  {w:"Medikament", a:"das", l:"A1", t:{en:"medicine", uk:"ліки"}},
  {w:"Meer", a:"das", l:"A1", t:{en:"sea", uk:"море"}},
  {w:"Mensch", a:"der", l:"A1", t:{en:"person", uk:"людина"}},
  {w:"Messer", a:"das", l:"A1", t:{en:"knife", uk:"ніж"}},
  {w:"Miete", a:"die", l:"A1", t:{en:"rent", uk:"оренда"}},
  {w:"Minute", a:"die", l:"A1", t:{en:"minute", uk:"хвилина"}},
  {w:"Mittag", a:"der", l:"A1", t:{en:"noon", uk:"полудень"}},
  {w:"Mittwoch", a:"der", l:"A1", t:{en:"Wednesday", uk:"середа"}},
  {w:"Möbel", a:"die", l:"A1", t:{en:"furniture", uk:"меблі"}},
  {w:"Moment", a:"der", l:"A1", t:{en:"moment", uk:"момент"}},
  {w:"Monat", a:"der", l:"A1", t:{en:"month", uk:"місяць"}},
  {w:"Montag", a:"der", l:"A1", t:{en:"Monday", uk:"понеділок"}},
  {w:"Morgen", a:"der", l:"A1", t:{en:"morning", uk:"ранок"}},
  {w:"Mund", a:"der", l:"A1", t:{en:"mouth", uk:"рот"}},
  {w:"Museum", a:"das", l:"A1", t:{en:"museum", uk:"музей"}},
  {w:"Musik", a:"die", l:"A1", t:{en:"music", uk:"музика"}},
  {w:"Mutter", a:"die", l:"A1", t:{en:"mother", uk:"мати"}},
  {w:"Nachbar", a:"der", l:"A1", t:{en:"neighbor", uk:"сусід"}},
  {w:"Nachricht", a:"die", l:"A1", t:{en:"message", uk:"повідомлення"}},
  {w:"Nacht", a:"die", l:"A1", t:{en:"night", uk:"ніч"}},
  {w:"Name", a:"der", l:"A1", t:{en:"name", uk:"ім'я"}},
  {w:"Nase", a:"die", l:"A1", t:{en:"nose", uk:"ніс"}},
  {w:"Natur", a:"die", l:"A1", t:{en:"nature", uk:"природа"}},
  {w:"Nebel", a:"der", l:"A1", t:{en:"fog", uk:"туман"}},
  {w:"Norden", a:"der", l:"A1", t:{en:"north", uk:"північ"}},
  {w:"Notfall", a:"der", l:"A1", t:{en:"emergency", uk:"надзвичайний випадок"}},
  {w:"Nummer", a:"die", l:"A1", t:{en:"number", uk:"номер"}},
  {w:"Obst", a:"das", l:"A1", t:{en:"fruit", uk:"фрукти"}},
  {w:"Oktober", a:"der", l:"A1", t:{en:"October", uk:"жовтень"}},
  {w:"Onkel", a:"der", l:"A1", t:{en:"uncle", uk:"дядько"}},
  {w:"Opa", a:"der", l:"A1", t:{en:"grandpa", uk:"дідусь"}},
  {w:"Orange", a:"die", l:"A1", t:{en:"orange", uk:"апельсин"}},
  {w:"Ordnung", a:"die", l:"A1", t:{en:"order", uk:"порядок"}},
  {w:"Ort", a:"der", l:"A1", t:{en:"place", uk:"місце"}},
  {w:"Osten", a:"der", l:"A1", t:{en:"east", uk:"схід"}},
  {w:"Paket", a:"das", l:"A1", t:{en:"package", uk:"пакет"}},
  {w:"Papier", a:"das", l:"A1", t:{en:"paper", uk:"папір"}},
  {w:"Park", a:"der", l:"A1", t:{en:"park", uk:"парк"}},
  {w:"Party", a:"die", l:"A1", t:{en:"party", uk:"вечірка"}},
  {w:"Pass", a:"der", l:"A1", t:{en:"passport", uk:"паспорт"}},
  {w:"Pause", a:"die", l:"A1", t:{en:"break", uk:"пауза"}},
  {w:"Person", a:"die", l:"A1", t:{en:"person", uk:"особа"}},
  {w:"Pfand", a:"das", l:"A1", t:{en:"deposit", uk:"застава"}},
  {w:"Pfeffer", a:"der", l:"A1", t:{en:"pepper", uk:"перець"}},
  {w:"Pferd", a:"das", l:"A1", t:{en:"horse", uk:"кінь"}},
  {w:"Pflanze", a:"die", l:"A1", t:{en:"plant", uk:"рослина"}},
  {w:"Platz", a:"der", l:"A1", t:{en:"place/square", uk:"місце/площа"}},
  {w:"Polizei", a:"die", l:"A1", t:{en:"police", uk:"поліція"}},
  {w:"Portion", a:"die", l:"A1", t:{en:"portion", uk:"порція"}},
  {w:"Post", a:"die", l:"A1", t:{en:"post", uk:"пошта"}},
  {w:"Preis", a:"der", l:"A1", t:{en:"price", uk:"ціна"}},
  {w:"Problem", a:"das", l:"A1", t:{en:"problem", uk:"проблема"}},
  {w:"Produkt", a:"das", l:"A1", t:{en:"product", uk:"продукт"}},
  {w:"Programm", a:"das", l:"A1", t:{en:"program", uk:"програма"}},
  {w:"Projekt", a:"das", l:"A1", t:{en:"project", uk:"проект"}},
  {w:"Prüfung", a:"die", l:"A1", t:{en:"exam", uk:"іспит"}},
  {w:"Punkt", a:"der", l:"A1", t:{en:"point", uk:"пункт"}},
  {w:"Quittung", a:"die", l:"A1", t:{en:"receipt", uk:"квитанція"}},
  {w:"Radio", a:"das", l:"A1", t:{en:"radio", uk:"радіо"}},
  {w:"Rathaus", a:"das", l:"A1", t:{en:"city hall", uk:"ратуша"}},
  {w:"Rechnung", a:"die", l:"A1", t:{en:"bill", uk:"рахунок"}},
  {w:"Regen", a:"der", l:"A1", t:{en:"rain", uk:"дощ"}},
  {w:"Region", a:"die", l:"A1", t:{en:"region", uk:"регіон"}},
  {w:"Reis", a:"der", l:"A1", t:{en:"rice", uk:"рис"}},
  {w:"Reise", a:"die", l:"A1", t:{en:"travel", uk:"подорож"}},
  {w:"Rezept", a:"das", l:"A1", t:{en:"recipe", uk:"рецепт"}},
  {w:"Rock", a:"der", l:"A1", t:{en:"skirt", uk:"спідниця"}},
  {w:"Rücken", a:"der", l:"A1", t:{en:"back", uk:"спина"}},
  {w:"Saft", a:"der", l:"A1", t:{en:"juice", uk:"сік"}},
  {w:"Salat", a:"der", l:"A1", t:{en:"salad", uk:"салат"}},
  {w:"Salz", a:"das", l:"A1", t:{en:"salt", uk:"сіль"}},
  {w:"Samstag", a:"der", l:"A1", t:{en:"Saturday", uk:"субота"}},
  {w:"Satz", a:"der", l:"A1", t:{en:"sentence", uk:"речення"}},
  {w:"Schal", a:"der", l:"A1", t:{en:"scarf", uk:"шарф"}},
  {w:"Schiff", a:"das", l:"A1", t:{en:"ship", uk:"корабель"}},
  {w:"Schild", a:"das", l:"A1", t:{en:"sign", uk:"щит/вивіска"}},
  {w:"Schirm", a:"der", l:"A1", t:{en:"umbrella", uk:"парасоля"}},
  {w:"Schlaf", a:"der", l:"A1", t:{en:"sleep", uk:"сон"}},
  {w:"Schloss", a:"das", l:"A1", t:{en:"castle", uk:"замок"}},
  {w:"Schluss", a:"der", l:"A1", t:{en:"end", uk:"завершення"}},
  {w:"Schlüssel", a:"der", l:"A1", t:{en:"key", uk:"ключ"}},
  {w:"Schmerz", a:"der", l:"A1", t:{en:"pain", uk:"біль"}},
  {w:"Schokolade", a:"die", l:"A1", t:{en:"chocolate", uk:"шоколад"}},
  {w:"Schrank", a:"der", l:"A1", t:{en:"closet", uk:"шафа"}},
  {w:"Schuh", a:"der", l:"A1", t:{en:"shoe", uk:"взуття"}},
  {w:"Schule", a:"die", l:"A1", t:{en:"school", uk:"школа"}},
  {w:"Schüler", a:"der", l:"A1", t:{en:"student", uk:"учень"}},
  {w:"Schwester", a:"die", l:"A1", t:{en:"sister", uk:"сестра"}},
  {w:"See", a:"der", l:"A1", t:{en:"lake", uk:"озеро"}},
  {w:"Seite", a:"die", l:"A1", t:{en:"page", uk:"сторінка"}},
  {w:"Sekunde", a:"die", l:"A1", t:{en:"second", uk:"секунда"}},
  {w:"September", a:"der", l:"A1", t:{en:"September", uk:"вересень"}},
  {w:"Service", a:"der", l:"A1", t:{en:"service", uk:"сервіс"}},
  {w:"Sessel", a:"der", l:"A1", t:{en:"armchair", uk:"крісло"}},
  {w:"Sofa", a:"das", l:"A1", t:{en:"sofa", uk:"диван"}},
  {w:"Sohn", a:"der", l:"A1", t:{en:"son", uk:"син"}},
  {w:"Sommer", a:"der", l:"A1", t:{en:"summer", uk:"літо"}},
  {w:"Sonne", a:"die", l:"A1", t:{en:"sun", uk:"сонце"}},
  {w:"Sonntag", a:"der", l:"A1", t:{en:"Sunday", uk:"неділя"}},
  {w:"Soße", a:"die", l:"A1", t:{en:"sauce", uk:"соус"}},
  {w:"Spaß", a:"der", l:"A1", t:{en:"fun", uk:"задоволення"}},
  {w:"Spiel", a:"das", l:"A1", t:{en:"game", uk:"гра"}},
  {w:"Sport", a:"der", l:"A1", t:{en:"sport", uk:"спорт"}},
  {w:"Sprache", a:"die", l:"A1", t:{en:"language", uk:"мова"}},
  {w:"Stadt", a:"die", l:"A1", t:{en:"city", uk:"місто"}},
  {w:"Station", a:"die", l:"A1", t:{en:"station", uk:"станція"}},
  {w:"Stau", a:"der", l:"A1", t:{en:"traffic jam", uk:"затор"}},
  {w:"Stelle", a:"die", l:"A1", t:{en:"position", uk:"місце/посада"}},
  {w:"Steuer", a:"die", l:"A1", t:{en:"tax", uk:"податок"}},
  {w:"Stift", a:"der", l:"A1", t:{en:"pen", uk:"олівець/ручка"}},
  {w:"Stock", a:"der", l:"A1", t:{en:"floor", uk:"поверх"}},
  {w:"Straße", a:"die", l:"A1", t:{en:"street", uk:"вулиця"}},
  {w:"Strom", a:"der", l:"A1", t:{en:"electricity", uk:"струм"}},
  {w:"Stück", a:"das", l:"A1", t:{en:"piece", uk:"шматок"}},
  {w:"Student", a:"der", l:"A1", t:{en:"student", uk:"студент"}},
  {w:"Studium", a:"das", l:"A1", t:{en:"study", uk:"навчання"}},
  {w:"Stuhl", a:"der", l:"A1", t:{en:"chair", uk:"стілець"}},
  {w:"Stunde", a:"die", l:"A1", t:{en:"hour", uk:"година"}},
  {w:"Süden", a:"der", l:"A1", t:{en:"south", uk:"південь"}},
  {w:"Supermarkt", a:"der", l:"A1", t:{en:"supermarket", uk:"супермаркет"}},
  {w:"Suppe", a:"die", l:"A1", t:{en:"soup", uk:"суп"}},
  {w:"Tag", a:"der", l:"A1", t:{en:"day", uk:"день"}},
  {w:"Tankstelle", a:"die", l:"A1", t:{en:"gas station", uk:"бензоколонка"}},
  {w:"Tante", a:"die", l:"A1", t:{en:"aunt", uk:"тітка"}},
  {w:"Tasche", a:"die", l:"A1", t:{en:"bag", uk:"сумка"}},
  {w:"Tasse", a:"die", l:"A1", t:{en:"cup", uk:"чашка"}},
  {w:"Taxi", a:"das", l:"A1", t:{en:"taxi", uk:"таксі"}},
  {w:"Tee", a:"der", l:"A1", t:{en:"tea", uk:"чай"}},
  {w:"Teil", a:"der/das", l:"A1", t:{en:"part", uk:"частина"}},
  {w:"Telefon", a:"das", l:"A1", t:{en:"telephone", uk:"телефон"}},
  {w:"Teller", a:"der", l:"A1", t:{en:"plate", uk:"тарілка"}},
  {w:"Teppich", a:"der", l:"A1", t:{en:"carpet", uk:"килим"}},
  {w:"Termin", a:"der", l:"A1", t:{en:"appointment", uk:"термін/зустріч"}},
  {w:"Text", a:"der", l:"A1", t:{en:"text", uk:"текст"}},
  {w:"Thema", a:"das", l:"A1", t:{en:"topic", uk:"тема"}},
  {w:"Ticket", a:"das", l:"A1", t:{en:"ticket", uk:"квиток"}},
  {w:"Tier", a:"das", l:"A1", t:{en:"animal", uk:"тварина"}},
  {w:"Tisch", a:"der", l:"A1", t:{en:"table", uk:"стіл"}},
  {w:"Tochter", a:"die", l:"A1", t:{en:"daughter", uk:"донька"}},
  {w:"Toilette", a:"die", l:"A1", t:{en:"toilet", uk:"туалет"}},
  {w:"Tomate", a:"die", l:"A1", t:{en:"tomate", uk:"помідор"}},
  {w:"Topf", a:"der", l:"A1", t:{en:"pot", uk:"каструля"}},
  {w:"Tourist", a:"der", l:"A1", t:{en:"tourist", uk:"турист"}},
  {w:"Training", a:"das", l:"A1", t:{en:"training", uk:"тренування"}},
  {w:"Transport", a:"der", l:"A1", t:{en:"transport", uk:"транспорт"}},
  {w:"Treppe", a:"die", l:"A1", t:{en:"stairs", uk:"сходи"}},
  {w:"Trinkgeld", a:"das", l:"A1", t:{en:"tip", uk:"чайові"}},
  {w:"Unfall", a:"der", l:"A1", t:{en:"accident", uk:"аварія"}},
  {w:"Universität", a:"die", l:"A1", t:{en:"university", uk:"університет"}},
  {w:"Unterricht", a:"der", l:"A1", t:{en:"lesson", uk:"заняття"}},
  {w:"Urlaub", a:"der", l:"A1", t:{en:"vacation", uk:"відпустка"}},
  {w:"Vater", a:"der", l:"A1", t:{en:"father", uk:"батько"}},
  {w:"Verbot", a:"das", l:"A1", t:{en:"prohibition", uk:"заборона"}},
  {w:"Verein", a:"der", l:"A1", t:{en:"association", uk:"клуб/спілка"}},
  {w:"Verkehr", a:"der", l:"A1", t:{en:"traffic", uk:"рух"}},
  {w:"Vermieter", a:"der", l:"A1", t:{en:"landlord", uk:"орендодавець"}},
  {w:"Verspätung", a:"die", l:"A1", t:{en:"delay", uk:"запізнення"}},
  {w:"Vertrag", a:"der", l:"A1", t:{en:"contract", uk:"контракт"}},
  {w:"Viertel", a:"das", l:"A1", t:{en:"quarter", uk:"чверть"}},
  {w:"Vogel", a:"der", l:"A1", t:{en:"bird", uk:"птах"}},
  {w:"Vorname", a:"der", l:"A1", t:{en:"first name", uk:"ім'я"}},
  {w:"Vormittag", a:"der", l:"A1", t:{en:"late morning", uk:"дополудня"}},
  {w:"Wagen", a:"der", l:"A1", t:{en:"car/wagon", uk:"автомобіль"}},
  {w:"Wald", a:"der", l:"A1", t:{en:"forest", uk:"ліс"}},
  {w:"Wand", a:"die", l:"A1", t:{en:"wall", uk:"стіна"}},
  {w:"Wasser", a:"das", l:"A1", t:{en:"water", uk:"вода"}},
  {w:"Weg", a:"der", l:"A1", t:{en:"way", uk:"шлях"}},
  {w:"Wein", a:"der", l:"A1", t:{en:"wine", uk:"вино"}},
  {w:"Welt", a:"die", l:"A1", t:{en:"world", uk:"світ"}},
  {w:"Werkstatt", a:"die", l:"A1", t:{en:"workshop", uk:"майстерня"}},
  {w:"Wetter", a:"das", l:"A1", t:{en:"weather", uk:"погода"}},
  {w:"Wind", a:"der", l:"A1", t:{en:"wind", uk:"вітер"}},
  {w:"Winter", a:"der", l:"A1", t:{en:"winter", uk:"зима"}},
  {w:"Woche", a:"die", l:"A1", t:{en:"week", uk:"тиждень"}},
  {w:"Wochenende", a:"das", l:"A1", t:{en:"weekend", uk:"вихідні"}},
  {w:"Wohnung", a:"die", l:"A1", t:{en:"apartment", uk:"квартира"}},
  {w:"Wolke", a:"die", l:"A1", t:{en:"cloud", uk:"хмара"}},
  {w:"Wort", a:"das", l:"A1", t:{en:"word", uk:"слово"}},
  {w:"Wunsch", a:"der", l:"A1", t:{en:"wish", uk:"бажання"}},
  {w:"Wurst", a:"die", l:"A1", t:{en:"sausage", uk:"ковбаса"}},
  {w:"Zahl", a:"die", l:"A1", t:{en:"number", uk:"число"}},
  {w:"Zahn", a:"der", l:"A1", t:{en:"tooth", uk:"зуб"}},
  {w:"Zeit", a:"die", l:"A1", t:{en:"time", uk:"час"}},
  {w:"Zeitschrift", a:"die", l:"A1", t:{en:"magazine", uk:"журнал"}},
  {w:"Zeitung", a:"die", l:"A1", t:{en:"newspaper", uk:"газета"}},
  {w:"Zentrum", a:"das", l:"A1", t:{en:"center", uk:"центр"}},
  {w:"Zettel", a:"der", l:"A1", t:{en:"note", uk:"записка"}},
  {w:"Zeugnis", a:"das", l:"A1", t:{en:"certificate", uk:"свідоцтво/атестат"}},
  {w:"Ziel", a:"das", l:"A1", t:{en:"goal", uk:"ціль"}},
  {w:"Zimmer", a:"das", l:"A1", t:{en:"room", uk:"кімната"}},
  {w:"Zoo", a:"der", l:"A1", t:{en:"zoo", uk:"зоопарк"}},
  {w:"Zucker", a:"der", l:"A1", t:{en:"sugar", uk:"цукор"}},
  {w:"Zug", a:"der", l:"A1", t:{en:"train", uk:"поїзд"}},
  {w:"Zukunft", a:"die", l:"A1", t:{en:"future", uk:"майбутнє"}},
  
  // --- LEVEL A2 (Daily Life & Social Integration) ---
  {w:"Ahnung", a:"die", l:"A2", t:{en:"idea/clue", uk:"уявлення/поняття"}},
  {w:"Alltag", a:"der", l:"A2", t:{en:"everyday life", uk:"буддень/повсякдення"}},
  {w:"Ampel", a:"die", l:"A2", t:{en:"traffic light", uk:"світлофор"}},
  {w:"Anfang", a:"der", l:"A2", t:{en:"beginning", uk:"початок"}},
  {w:"Angebot", a:"das", l:"A2", t:{en:"offer", uk:"пропозиція"}},
  {w:"Angst", a:"die", l:"A2", t:{en:"fear", uk:"страх"}},
  {w:"Ankunft", a:"die", l:"A2", t:{en:"arrival", uk:"прибуття"}},
  {w:"Anmeldung", a:"die", l:"A2", t:{en:"registration", uk:"реєстрація"}},
  {w:"Anruf", a:"der", l:"A2", t:{en:"phone call", uk:"дзвінок"}},
  {w:"Anschluss", a:"der", l:"A2", t:{en:"connection", uk:"підключення"}},
  {w:"Ansicht", a:"die", l:"A2", t:{en:"view/opinion", uk:"погляд/думка"}},
  {w:"Anspruch", a:"der", l:"A2", t:{en:"claim/right", uk:"вимога/право"}},
  {w:"Antrag", a:"der", l:"A2", t:{en:"application/form", uk:"заява/заявка"}},
  {w:"Antwort", a:"die", l:"A2", t:{en:"answer", uk:"відповідь"}},
  {w:"Anzug", a:"der", l:"A2", t:{en:"suit", uk:"костюм"}},
  {w:"Apotheker", a:"der", l:"A2", t:{en:"pharmacist", uk:"фармацевт"}},
  {w:"Apparat", a:"der", l:"A2", t:{en:"apparatus/device", uk:"апарат/прилад"}},
  {w:"Appetit", a:"der", l:"A2", t:{en:"appetite", uk:"апетит"}},
  {w:"Arbeitgeber", a:"der", l:"A2", t:{en:"employer", uk:"роботодавець"}},
  {w:"Arbeitnehmer", a:"der", l:"A2", t:{en:"employee", uk:"найманий працівник"}},
  {w:"Arbeitsplatz", a:"der", l:"A2", t:{en:"workplace", uk:"робоче місце"}},
  {w:"Armut", a:"die", l:"A2", t:{en:"poverty", uk:"бідність"}},
  {w:"Artikel", a:"der", l:"A2", t:{en:"article", uk:"стаття/артикль"}},
  {w:"Asyl", a:"das", l:"A2", t:{en:"asylum", uk:"притулок"}},
  {w:"Aufenthalt", a:"der", l:"A2", t:{en:"stay", uk:"перебування"}},
  {w:"Aufgabe", a:"die", l:"A2", t:{en:"task", uk:"завдання"}},
  {w:"Aufzug", a:"der", l:"A2", t:{en:"elevator", uk:"ліфт"}},
  {w:"Ausländer", a:"der", l:"A2", t:{en:"foreigner", uk:"іноземець"}},
  {w:"Ausleihfrist", a:"die", l:"A2", t:{en:"loan period", uk:"термін прокату"}},
  {w:"Ausweis", a:"der", l:"A2", t:{en:"ID card", uk:"посвідчення"}},
  {w:"Autor", a:"der", l:"A2", t:{en:"author", uk:"автор"}},
  {w:"Bäckerei", a:"die", l:"A2", t:{en:"bakery", uk:"пекарня"}},
  {w:"Badewanne", a:"die", l:"A2", t:{en:"bathtub", uk:"ванна"}},
  {w:"Becher", a:"der", l:"A2", t:{en:"cup/beaker", uk:"кухоль/стакан"}},
  {w:"Bedarf", a:"der", l:"A2", t:{en:"need/demand", uk:"потреба/попит"}},
  {w:"Bedingung", a:"die", l:"A2", t:{en:"condition", uk:"умова"}},
  {w:"Begeisterung", a:"die", l:"A2", t:{en:"enthusiasm", uk:"захват"}},
  {w:"Beginn", a:"der", l:"A2", t:{en:"start", uk:"початок"}},
  {w:"Begründung", a:"die", l:"A2", t:{en:"justification", uk:"обґрунтування"}},
  {w:"Behörde", a:"die", l:"A2", t:{en:"authority", uk:"орган влади/відомство"}},
  {w:"Beleg", a:"der", l:"A2", t:{en:"receipt/proof", uk:"квитанція/чек"}},
  {w:"Belohnung", a:"die", l:"A2", t:{en:"reward", uk:"нагорода"}},
  {w:"Beratung", a:"die", l:"A2", t:{en:"consultation", uk:"консультація"}},
  {w:"Bereich", a:"der", l:"A2", t:{en:"area/field", uk:"сфера/область"}},
  {w:"Bericht", a:"der", l:"A2", t:{en:"report", uk:"звіт"}},
  {w:"Bescheid", a:"der", l:"A2", t:{en:"decision/notice", uk:"рішення/сповіщення"}},
  {w:"Beschreibung", a:"die", l:"A2", t:{en:"description", uk:"опис"}},
  {w:"Beschwerde", a:"die", l:"A2", t:{en:"complaint", uk:"скарга"}},
  {w:"Besitz", a:"der", l:"A2", t:{en:"possession/property", uk:"власність/володіння"}},
  {w:"Besonderheit", a:"die", l:"A2", t:{en:"peculiarity", uk:"особливість"}},
  {w:"Bestätigung", a:"die", l:"A2", t:{en:"confirmation", uk:"підтвердження"}},
  {w:"Bestellung", a:"die", l:"A2", t:{en:"order", uk:"замовлення"}},
  {w:"Besuch", a:"der", l:"A2", t:{en:"visit", uk:"візит/відвідування"}},
  {w:"Betrieb", a:"der", l:"A2", t:{en:"company/operation", uk:"підприємство"}},
  {w:"Betrug", a:"der", l:"A2", t:{en:"fraud", uk:"шахрайство"}},
  {w:"Bevölkerung", a:"die", l:"A2", t:{en:"population", uk:"населення"}},
  {w:"Beweis", a:"der", l:"A2", t:{en:"proof", uk:"доказ"}},
  {w:"Bewerber", a:"der", l:"A2", t:{en:"applicant", uk:"претендент/заявник"}},
  {w:"Bewerbung", a:"die", l:"A2", t:{en:"application", uk:"заява про прийом на роботу"}},
  {w:"Beziehung", a:"die", l:"A2", t:{en:"relationship", uk:"стосунки"}},
  {w:"Bibliothek", a:"die", l:"A2", t:{en:"library", uk:"бібліотека"}},
  {w:"Biologie", a:"die", l:"A2", t:{en:"biology", uk:"біологія"}},
  {w:"Blick", a:"der", l:"A2", t:{en:"view/glance", uk:"погляд"}},
  {w:"Blitz", a:"der", l:"A2", t:{en:"lightning", uk:"блискавка"}},
  {w:"Blut", a:"das", l:"A2", t:{en:"blood", uk:"кров"}},
  {w:"Bombe", a:"die", l:"A2", t:{en:"bomb", uk:"бомба"}},
  {w:"Boot", a:"das", l:"A2", t:{en:"boat", uk:"човен"}},
  {w:"Botschaft", a:"die", l:"A2", t:{en:"message/embassy", uk:"послання/посольство"}},
  {w:"Brand", a:"der", l:"A2", t:{en:"fire", uk:"пожежа"}},
  {w:"Braten", a:"der", l:"A2", t:{en:"roast meat", uk:"печеня"}},
  {w:"Brauch", a:"der", l:"A2", t:{en:"custom/tradition", uk:"звичай"}},
  {w:"Brille", a:"die", l:"A2", t:{en:"glasses", uk:"окуляри"}},
  {w:"Broschüre", a:"die", l:"A2", t:{en:"brochure", uk:"брошура"}},
  {w:"Brücke", a:"die", l:"A2", t:{en:"bridge", uk:"міст"}},
  {w:"Brunnen", a:"der", l:"A2", t:{en:"well/fountain", uk:"криниця/фонтан"}},
  {w:"Brust", a:"die", l:"A2", t:{en:"chest", uk:"груди"}},
  {w:"Bühne", a:"die", l:"A2", t:{en:"stage", uk:"сцена"}},
  {w:"Bund", a:"der", l:"A2", t:{en:"federation/union", uk:"федерація/союз"}},
  {w:"Bürger", a:"der", l:"A2", t:{en:"citizen", uk:"громадянин"}},
  {w:"Bürgermeister", a:"der", l:"A2", t:{en:"mayor", uk:"мер"}},
  {w:"Büro", a:"das", l:"A2", t:{en:"office", uk:"офіс"}},
  {w:"Charakter", a:"der", l:"A2", t:{en:"character", uk:"характер"}},
  {w:"Couch", a:"die", l:"A2", t:{en:"couch", uk:"диван"}},
  {w:"Dach", a:"das", l:"A2", t:{en:"roof", uk:"дах"}},
  {w:"Dauer", a:"die", l:"A2", t:{en:"duration", uk:"тривалість"}},
  {w:"Decke", a:"die", l:"A2", t:{en:"blanket/ceiling", uk:"ковдра/стеля"}},
  {w:"Demokratie", a:"die", l:"A2", t:{en:"democracy", uk:"демократія"}},
  {w:"Denkmal", a:"das", l:"A2", t:{en:"monument", uk:"пам'ятник"}},
  {w:"Detail", a:"das", l:"A2", t:{en:"detail", uk:"деталь"}},
  {w:"Dialekt", a:"der", l:"A2", t:{en:"dialect", uk:"діалект"}},
  {w:"Dialog", a:"der", l:"A2", t:{en:"dialogue", uk:"діалог"}},
  {w:"Diät", a:"die", l:"A2", t:{en:"diet", uk:"дієта"}},
  {w:"Differenz", a:"die", l:"A2", t:{en:"difference", uk:"різниця"}},
  {w:"Dokument", a:"das", l:"A2", t:{en:"document", uk:"документ"}},
  {w:"Dose", a:"die", l:"A2", t:{en:"can/tin", uk:"бляшанка"}},
  {w:"Drache", a:"der", l:"A2", t:{en:"dragon/kite", uk:"дракон/змій"}},
  {w:"Dreck", a:"der", l:"A2", t:{en:"dirt", uk:"бруд"}},
  {w:"Druck", a:"der", l:"A2", t:{en:"pressure", uk:"тиск"}},
  {w:"Dusche", a:"die", l:"A2", t:{en:"shower", uk:"душ"}},
  {w:"Ecke", a:"die", l:"A2", t:{en:"corner", uk:"кут"}},
  {w:"Eindruck", a:"der", l:"A2", t:{en:"impression", uk:"враження"}},
  {w:"Einzug", a:"der", l:"A2", t:{en:"moving in", uk:"в'їзд (у житло)"}},
  {w:"Empfang", a:"der", l:"A2", t:{en:"reception", uk:"прийом"}},
  {w:"Energie", a:"die", l:"A2", t:{en:"energy", uk:"енергія"}},
  {w:"Enkel", a:"der", l:"A2", t:{en:"grandson", uk:"онук"}},
  {w:"Enttäuschung", a:"die", l:"A2", t:{en:"disappointment", uk:"розчарування"}},
  {w:"Ergebnis", a:"das", l:"A2", t:{en:"result", uk:"результат"}},
  {w:"Erlaubnis", a:"die", l:"A2", t:{en:"permission", uk:"дозвіл"}},
  {w:"Ermäßigung", a:"die", l:"A2", t:{en:"discount", uk:"знижка"}},
  {w:"Ernst", a:"der", l:"A2", t:{en:"seriousness", uk:"серйозність"}},
  {w:"Ernte", a:"die", l:"A2", t:{en:"harvest", uk:"урожай"}},
  {w:"Erzählung", a:"die", l:"A2", t:{en:"story/narrative", uk:"оповідання"}},
  {w:"Fabrik", a:"die", l:"A2", t:{en:"factory", uk:"фабрика"}},
  {w:"Fach", a:"das", l:"A2", t:{en:"subject/compartment", uk:"предмет/відділення"}},
  {w:"Fahrer", a:"der", l:"A2", t:{en:"driver", uk:"водій"}},
  {w:"Fahrplan", a:"der", l:"A2", t:{en:"timetable", uk:"розклад руху"}},
  {w:"Fahrstuhl", a:"der", l:"A2", t:{en:"elevator/lift", uk:"ліфт"}},
  {w:"Fantasie", a:"die", l:"A2", t:{en:"imagination", uk:"фантазія"}},
  {w:"Feier", a:"die", l:"A2", t:{en:"celebration", uk:"святкування"}},
  {w:"Feiertag", a:"der", l:"A2", t:{en:"public holiday", uk:"свято (вихідний)"}},
  {w:"Fett", a:"das", l:"A2", t:{en:"fat", uk:"жир"}},
  {w:"Figur", a:"die", l:"A2", t:{en:"figure", uk:"фігура"}},
  {w:"Firma", a:"die", l:"A2", t:{en:"company", uk:"фірма"}},
  {w:"Fläche", a:"die", l:"A2", t:{en:"area/surface", uk:"площа/поверхня"}},
  {w:"Fleck", a:"der", l:"A2", t:{en:"spot/stain", uk:"пляма"}},
  {w:"Fliege", a:"die", l:"A2", t:{en:"fly", uk:"муха"}},
  {w:"Flirt", a:"der", l:"A2", t:{en:"flirtation", uk:"флірт"}},
  {w:"Fluch", a:"der", l:"A2", t:{en:"curse", uk:"прокляття"}},
  {w:"Fluss", a:"der", l:"A2", t:{en:"river", uk:"річка"}},
  {w:"Form", a:"die", l:"A2", t:{en:"form/shape", uk:"форма"}},
  {w:"Forst", a:"der", l:"A2", t:{en:"forest/woods", uk:"лісництво"}},
  {w:"Fortschritt", a:"der", l:"A2", t:{en:"progress", uk:"прогрес"}},
  {w:"Fotoapparat", a:"der", l:"A2", t:{en:"camera", uk:"фотоапарат"}},
  {w:"Freude", a:"die", l:"A2", t:{en:"joy", uk:"радість"}},
  {w:"Friede", a:"der", l:"A2", t:{en:"peace", uk:"мир"}},
  {w:"Friseur", a:"der", l:"A2", t:{en:"hairdresser", uk:"перукар"}},
  {w:"Frist", a:"die", l:"A2", t:{en:"deadline/period", uk:"термін/дедлайн"}},
  {w:"Funk", a:"der", l:"A2", t:{en:"radio", uk:"радіо/радіозв'язок"}},
  {w:"Furcht", a:"die", l:"A2", t:{en:"fear/dread", uk:"страх/острах"}},
  {w:"Gebäck", a:"das", l:"A2", t:{en:"pastry", uk:"випічка"}},
  {w:"Gedanke", a:"der", l:"A2", t:{en:"thought", uk:"думка"}},
  {w:"Geduld", a:"die", l:"A2", t:{en:"patience", uk:"терпіння"}},
  {w:"Gefahr", a:"die", l:"A2", t:{en:"danger", uk:"небезпека"}},
  {w:"Gefühl", a:"das", l:"A2", t:{en:"feeling", uk:"почуття"}},
  {w:"Gegenteil", a:"das", l:"A2", t:{en:"opposite", uk:"протилежність"}},
  {w:"Gehalt", a:"das", l:"A2", t:{en:"salary", uk:"зарплата"}},
  {w:"Geheimnis", a:"das", l:"A2", t:{en:"secret", uk:"таємниця"}},
  {w:"Gehirn", a:"das", l:"A2", t:{en:"brain", uk:"мозок"}},
  {w:"Geisel", a:"die", l:"A2", t:{en:"hostage", uk:"заручник"}},
  {w:"Geist", a:"der", l:"A2", t:{en:"spirit/mind", uk:"дух/розум"}},
  {w:"Generation", a:"die", l:"A2", t:{en:"generation", uk:"покоління"}},
  {w:"Genuss", a:"der", l:"A2", t:{en:"enjoyment", uk:"насолода"}},
  {w:"Geräusch", a:"das", l:"A2", t:{en:"noise", uk:"шум"}},
  {w:"Gerechtigkeit", a:"die", l:"A2", t:{en:"justice", uk:"справедливість"}},
  {w:"Geruch", a:"der", l:"A2", t:{en:"smell", uk:"запах"}},
  {w:"Geschmack", a:"der", l:"A2", t:{en:"taste", uk:"смак"}},
  {w:"Gesetz", a:"das", l:"A2", t:{en:"law", uk:"закон"}},
  {w:"Gewalt", a:"die", l:"A2", t:{en:"violence", uk:"насилля"}},
  {w:"Gewicht", a:"das", l:"A2", t:{en:"weight", uk:"вага"}},
  {w:"Gewissen", a:"das", l:"A2", t:{en:"conscience", uk:"совість"}},
  {w:"Gewitter", a:"das", l:"A2", t:{en:"thunderstorm", uk:"гроза"}},
  {w:"Gift", a:"das", l:"A2", t:{en:"poison", uk:"отрута"}},
  {w:"Gold", a:"das", l:"A2", t:{en:"gold", uk:"золото"}},
  {w:"Grenze", a:"die", l:"A2", t:{en:"border", uk:"кордон"}},
  {w:"Grippe", a:"die", l:"A2", t:{en:"flu", uk:"грип"}},
  {w:"Grund", a:"der", l:"A2", t:{en:"reason/ground", uk:"причина/земля"}},
  {w:"Grundstück", a:"das", l:"A2", t:{en:"property/plot", uk:"земельна ділянка"}},
  {w:"Gummi", a:"der/das", l:"A2", t:{en:"rubber/eraser", uk:"гума/гумка"}},
  {w:"Gürtel", a:"der", l:"A2", t:{en:"belt", uk:"пасок"}},
  {w:"Hafen", a:"der", l:"A2", t:{en:"port/harbor", uk:"порт"}},
  {w:"Hälfte", a:"die", l:"A2", t:{en:"half", uk:"половина"}},
  {w:"Halle", a:"die", l:"A2", t:{en:"hall", uk:"зал"}},
  {w:"Hammer", a:"der", l:"A2", t:{en:"hammer", uk:"молоток"}},
  {w:"Handtuch", a:"das", l:"A2", t:{en:"towel", uk:"рушник"}},
  {w:"Harmonie", a:"die", l:"A2", t:{en:"harmony", uk:"гармонія"}},
  {w:"Hass", a:"der", l:"A2", t:{en:"hatred", uk:"ненависть"}},
  {w:"Hauptstadt", a:"die", l:"A2", t:{en:"capital", uk:"столиця"}},
  {w:"Haut", a:"die", l:"A2", t:{en:"skin", uk:"шкіра"}},
  {w:"Heim", a:"das", l:"A2", t:{en:"home/hostel", uk:"дім/притулок"}},
  {w:"Held", a:"der", l:"A2", t:{en:"hero", uk:"герой"}},
  {w:"Herd", a:"der", l:"A2", t:{en:"stove", uk:"плита"}},
  {w:"Herkunft", a:"die", l:"A2", t:{en:"origin", uk:"походження"}},
  {w:"Herrschaft", a:"die", l:"A2", t:{en:"rule/dominion", uk:"панування"}},
  {w:"Herz", a:"das", l:"A2", t:{en:"heart", uk:"серце"}},
  {w:"Himmel", a:"der", l:"A2", t:{en:"sky/heaven", uk:"небо"}},
  {w:"Hitze", a:"die", l:"A2", t:{en:"heat", uk:"спека"}},
  {w:"Hoffnung", a:"die", l:"A2", t:{en:"hope", uk:"надія"}},
  {w:"Höhe", a:"die", l:"A2", t:{en:"height", uk:"висота"}},
  {w:"Holz", a:"das", l:"A2", t:{en:"wood", uk:"деревина"}},
  {w:"Honig", a:"der", l:"A2", t:{en:"honey", uk:"мед"}},
  {w:"Horoskop", a:"das", l:"A2", t:{en:"horoscope", uk:"гороскоп"}},
  {w:"Humor", a:"der", l:"A2", t:{en:"humor", uk:"гумор"}},
  {w:"Hupe", a:"die", l:"A2", t:{en:"horn", uk:"сигнал автомобіля"}},
  {w:"Hut", a:"der", l:"A2", t:{en:"hat", uk:"капелюх"}},
  {w:"Industrie", a:"die", l:"A2", t:{en:"industry", uk:"промисловість"}},
  {w:"Infektion", a:"die", l:"A2", t:{en:"infection", uk:"інфекція"}},
  {w:"Inflation", a:"die", l:"A2", t:{en:"inflation", uk:"інфляція"}},
  {w:"Insekt", a:"das", l:"A2", t:{en:"insect", uk:"комаха"}},
  {w:"Instrument", a:"das", l:"A2", t:{en:"instrument", uk:"інструмент"}},
  {w:"Interview", a:"das", l:"A2", t:{en:"interview", uk:"інтерв'ю"}},
  {w:"Irrtum", a:"der", l:"A2", t:{en:"error/mistake", uk:"помилка"}},
  {w:"Jagd", a:"die", l:"A2", t:{en:"hunt/hunting", uk:"полювання"}},
  {w:"Jammer", a:"der", l:"A2", t:{en:"misery/pity", uk:"жаль/горе"}},
  {w:"Jugend", a:"die", l:"A2", t:{en:"youth", uk:"молодь"}},
  {w:"Justiz", a:"die", l:"A2", t:{en:"justice system", uk:"юстиція"}},
  {w:"Kaka", a:"der", l:"A2", t:{en:"cocoa", uk:"какао"}},
  {w:"Kälte", a:"die", l:"A2", t:{en:"cold", uk:"холод"}},
  {w:"Kampf", a:"der", l:"A2", t:{en:"fight/struggle", uk:"боротьба/бій"}},
  {w:"Kaninchen", a:"das", l:"A2", t:{en:"rabbit", uk:"кролик"}},
  {w:"Kante", a:"die", l:"A2", t:{en:"edge", uk:"край/ребро"}},
  {w:"Kanton", a:"der", l:"A2", t:{en:"canton", uk:"кантон"}},
  {w:"Kanzler", a:"der", l:"A2", t:{en:"chancellor", uk:"канцлер"}},
  {w:"Kapital", a:"das", l:"A2", t:{en:"capital", uk:"капітал"}},
  {w:"Kapitel", a:"das", l:"A2", t:{en:"chapter", uk:"розділ"}},
  {w:"Karre", a:"die", l:"A2", t:{en:"cart/barrow", uk:"тачка"}},
  {w:"Karriere", a:"die", l:"A2", t:{en:"career", uk:"кар'єра"}},
  {w:"Karton", a:"der", l:"A2", t:{en:"cardboard box", uk:"картонна коробка"}},
  {w:"Katastrophe", a:"die", l:"A2", t:{en:"catastrophe", uk:"катастрофа"}},
  {w:"Kauf", a:"der", l:"A2", t:{en:"purchase", uk:"купівля"}},
  {w:"Kehle", a:"die", l:"A2", t:{en:"throat", uk:"горло"}},
  {w:"Kenntnis", a:"die", l:"A2", t:{en:"knowledge", uk:"знання"}},
  {w:"Kennwort", a:"das", l:"A2", t:{en:"password", uk:"пароль"}},
  {w:"Kern", a:"der", l:"A2", t:{en:"core/seed", uk:"ядро/кісточка"}},
  {w:"Kissen", a:"das", l:"A2", t:{en:"pillow", uk:"подушка"}},
  {w:"Klang", a:"der", l:"A2", t:{en:"sound", uk:"звучання"}},
  {w:"Klassik", a:"die", l:"A2", t:{en:"classic", uk:"класика"}},
  {w:"Klima", a:"das", l:"A2", t:{en:"climate", uk:"клімат"}},
  {w:"Klingel", a:"die", l:"A2", t:{en:"bell", uk:"дзвінок"}},
  {w:"Klinik", a:"die", l:"A2", t:{en:"clinic", uk:"клініка"}},
  {w:"Klumpen", a:"der", l:"A2", t:{en:"lump/clot", uk:"грудка"}},
  {w:"Knie", a:"das", l:"A2", t:{en:"knee", uk:"коліно"}},
  {w:"Knopf", a:"der", l:"A2", t:{en:"button", uk:"гудзик"}},
  {w:"Koch", a:"der", l:"A2", t:{en:"cook/chef", uk:"кухар"}},
  {w:"Kohl", a:"der", l:"A2", t:{en:"cabbage", uk:"капуста"}},
  {w:"Komma", a:"das", l:"A2", t:{en:"comma", uk:"кома"}},
  {w:"Kommissar", a:"der", l:"A2", t:{en:"commissioner", uk:"комісар"}},
  {w:"Kompliment", a:"das", l:"A2", t:{en:"compliment", uk:"комплімент"}},
  {w:"Kompromiss", a:"der", l:"A2", t:{en:"compromise", uk:"компроміс"}},
  {w:"Konflikt", a:"der", l:"A2", t:{en:"conflict", uk:"конфлікт"}},
  {w:"König", a:"der", l:"A2", t:{en:"king", uk:"король"}},
  {w:"Konkurrenz", a:"die", l:"A2", t:{en:"competition", uk:"конкуренція"}},
  {w:"Konsum", a:"der", l:"A2", t:{en:"consumption", uk:"споживання"}},
  {w:"Konzentrat", a:"das", l:"A2", t:{en:"concentrate", uk:"концентрат"}},
  {w:"Konzert", a:"das", l:"A2", t:{en:"concert", uk:"концерт"}},
  {w:"Kopfhörer", a:"der", l:"A2", t:{en:"headphones", uk:"навушники"}},
  {w:"Kopie", a:"die", l:"A2", t:{en:"copy", uk:"копія"}},
  {w:"Korrektur", a:"die", l:"A2", t:{en:"correction", uk:"виправлення"}},
  {w:"Korridor", a:"der", l:"A2", t:{en:"corridor", uk:"коридор"}},
  {w:"Kraft", a:"die", l:"A2", t:{en:"strength/power", uk:"сила"}},
  {w:"Kredit", a:"der", l:"A2", t:{en:"credit/loan", uk:"кредит"}},
  {w:"Kreis", a:"der", l:"A2", t:{en:"circle/district", uk:"коло/район"}},
  {w:"Kreuz", a:"das", l:"A2", t:{en:"cross", uk:"хрест"}},
  {w:"Krieg", a:"der", l:"A2", t:{en:"war", uk:"війна"}},
  {w:"Krise", a:"die", l:"A2", t:{en:"crisis", uk:"криза"}},
  {w:"Kritik", a:"die", l:"A2", t:{en:"criticism", uk:"критика"}},
  {w:"Kunst", a:"die", l:"A2", t:{en:"art", uk:"мистецтво"}},
  {w:"Kunststoff", a:"der", l:"A2", t:{en:"plastic", uk:"пластмаса"}},
  {w:"Kur", a:"die", l:"A2", t:{en:"cure/spa treatment", uk:"курс лікування"}},
  {w:"Küste", a:"die", l:"A2", t:{en:"coast", uk:"узбережжя"}},
  {w:"Lärm", a:"der", l:"A2", t:{en:"noise", uk:"шум"}},
  {w:"Last", a:"die", l:"A2", t:{en:"load/burden", uk:"вантаж/тягар"}},
  {w:"Laub", a:"das", l:"A2", t:{en:"leaves/foliage", uk:"листя"}},
  {w:"Lauf", a:"der", l:"A2", t:{en:"run/course", uk:"біг/перебіг"}},
  {w:"Laune", a:"die", l:"A2", t:{en:"mood", uk:"настрій"}},
  {w:"Lautsprecher", a:"der", l:"A2", t:{en:"speaker", uk:"динамік"}},
  {w:"Leber", a:"die", l:"A2", t:{en:"liver", uk:"печінка"}},
  {w:"Leder", a:"das", l:"A2", t:{en:"leather", uk:"шкіра (матеріал)"}},
  {w:"Lehre", a:"die", l:"A2", t:{en:"apprenticeship/teaching", uk:"навчання"}},
  {w:"Leib", a:"der", l:"A2", t:{en:"body", uk:"тіло"}},
  {w:"Leiche", a:"die", l:"A2", t:{en:"corpse", uk:"труп"}},
  {w:"Leid", a:"das", l:"A2", t:{en:"suffering/sorrow", uk:"страждання/жаль"}},
  {w:"Leitung", a:"die", l:"A2", t:{en:"management/pipe", uk:"керівництво/провід"}},
  {w:"Lektüre", a:"die", l:"A2", t:{en:"reading material", uk:"читання/література"}},
  {w:"Lenker", a:"der", l:"A2", t:{en:"handlebar/driver", uk:"кермо"}},
  {w:"Leser", a:"der", l:"A2", t:{en:"reader", uk:"читач"}},
  {w:"Lexikon", a:"das", l:"A2", t:{en:"lexicon/encyclopedia", uk:"словник/енциклопедія"}},
  {w:"Liebe", a:"die", l:"A2", t:{en:"love", uk:"любов"}},
  {w:"Liege", a:"die", l:"A2", t:{en:"couch/lounger", uk:"лежак"}},
  {w:"Lift", a:"der", l:"A2", t:{en:"lift/elevator", uk:"ліфт"}},
  {w:"Linie", a:"die", l:"A2", t:{en:"line", uk:"лінія"}},
  {w:"Liste", a:"die", l:"A2", t:{en:"list", uk:"список"}},
  {w:"Loch", a:"das", l:"A2", t:{en:"hole", uk:"дірка"}},
  {w:"Lohn", a:"der", l:"A2", t:{en:"wage/reward", uk:"зарплата"}},
  {w:"Lösung", a:"die", l:"A2", t:{en:"solution", uk:"рішення"}},
  {w:"Lüge", a:"die", l:"A2", t:{en:"lie", uk:"брехня"}},
  {w:"Lunge", a:"die", l:"A2", t:{en:"lung", uk:"легеня"}},
  {w:"Luxus", a:"der", l:"A2", t:{en:"luxury", uk:"розкіш"}},
  {w:"Magnet", a:"der", l:"A2", t:{en:"magnet", uk:"магніт"}},
  {w:"Mahnung", a:"die", l:"A2", t:{en:"reminder/warning", uk:"нагадування/попередження"}},
  {w:"Malerei", a:"die", l:"A2", t:{en:"painting", uk:"живопис"}},
  {w:"Mama", a:"die", l:"A2", t:{en:"mom", uk:"мама"}},
  {w:"Mangel", a:"der", l:"A2", t:{en:"lack/deficiency", uk:"нестача"}},
  {w:"Mannschaft", a:"die", l:"A2", t:{en:"team", uk:"команда"}},
  {w:"Märchen", a:"das", l:"A2", t:{en:"fairy tale", uk:"казка"}},
  {w:"Marine", a:"die", l:"A2", t:{en:"navy", uk:"флот"}},
  {w:"Maske", a:"die", l:"A2", t:{en:"mask", uk:"маска"}},
  {w:"Material", a:"das", l:"A2", t:{en:"material", uk:"матеріал"}},
  {w:"Mathematik", a:"die", l:"A2", t:{en:"mathematics", uk:"математика"}},
  {w:"Matratze", a:"die", l:"A2", t:{en:"mattress", uk:"матрац"}},
  {w:"Mauer", a:"die", l:"A2", t:{en:"wall (outside)", uk:"стіна (зовнішня)"}},
  {w:"Mechaniker", a:"der", l:"A2", t:{en:"mechanic", uk:"механік"}},
  {w:"Medizin", a:"die", l:"A2", t:{en:"medicine", uk:"медицина"}},
  {w:"Mehl", a:"das", l:"A2", t:{en:"flour", uk:"борошно"}},
  {w:"Meinung", a:"die", l:"A2", t:{en:"opinion", uk:"думка"}},
  {w:"Menge", a:"die", l:"A2", t:{en:"amount/quantity", uk:"кількість"}},
  {w:"Messung", a:"die", l:"A2", t:{en:"measurement", uk:"вимірювання"}},
  {w:"Metall", a:"das", l:"A2", t:{en:"metal", uk:"метал"}},
  {w:"Methode", a:"die", l:"A2", t:{en:"method", uk:"метод"}},
  {w:"Mieter", a:"der", l:"A2", t:{en:"tenant", uk:"орендар"}},
  {w:"Migration", a:"die", l:"A2", t:{en:"migration", uk:"міграція"}},
  {w:"Mikrofon", a:"das", l:"A2", t:{en:"microphone", uk:"мікрофон"}},
  {w:"Million", a:"die", l:"A2", t:{en:"million", uk:"мільйон"}},
  {w:"Minister", a:"der", l:"A2", t:{en:"minister", uk:"міністр"}},
  {w:"Mitglied", a:"das", l:"A2", t:{en:"member", uk:"член (організації)"}},
  {w:"Mitteilung", a:"die", l:"A2", t:{en:"message/notification", uk:"повідомлення"}},
  {w:"Modell", a:"das", l:"A2", t:{en:"model", uk:"модель"}},
  {w:"Mond", a:"der", l:"A2", t:{en:"moon", uk:"місяць (небесне тіло)"}},
  {w:"Monitor", a:"der", l:"A2", t:{en:"monitor", uk:"монітор"}},
  {w:"Moral", a:"die", l:"A2", t:{en:"moral/morality", uk:"мораль"}},
  {w:"Mord", a:"der", l:"A2", t:{en:"murder", uk:"вбивство"}},
  {w:"Motivation", a:"die", l:"A2", t:{en:"motivation", uk:"мотивація"}},
  {w:"Motor", a:"der", l:"A2", t:{en:"engine", uk:"двигун"}},
  {w:"Müll", a:"der", l:"A2", t:{en:"trash/garbage", uk:"сміття"}},
  {w:"Münze", a:"die", l:"A2", t:{en:"coin", uk:"монета"}},
  {w:"Mut", a:"der", l:"A2", t:{en:"courage", uk:"мужність/відвага"}},
  {w:"Mythe", a:"die", l:"A2", t:{en:"myth", uk:"міф"}}
];
