const rawData = [
  // --- LEVEL A1 (The Basics) ---
  {w:"Abend",a:"der",l:"A1",t:{en:"evening",uk:"вечір"}},
  {w:"Adresse",a:"die",l:"A1",t:{en:"address",uk:"адреса"}},
  {w:"Apfel",a:"der",l:"A1",t:{en:"apple",uk:"яблуко"}},
  {w:"Arm",a:"der",l:"A1",t:{en:"arm",uk:"рука"}},
  {w:"Arzt",a:"der",l:"A1",t:{en:"doctor",uk:"лікар"}},
  {w:"Auge",a:"das",l:"A1",t:{en:"eye",uk:"око"}},
  {w:"Auto",a:"das",l:"A1",t:{en:"car",uk:"автомобіль"}},
  {w:"Bad",a:"das",l:"A1",t:{en:"bathroom",uk:"ванна кімната"}},
  {w:"Bahnhof",a:"der",l:"A1",t:{en:"train station",uk:"вокзал"}},
  {w:"Bank",a:"die",l:"A1",t:{en:"bank",uk:"банк"}},
  {w:"Bett",a:"das",l:"A1",t:{en:"bed",uk:"ліжко"}},
  {w:"Bild",a:"das",l:"A1",t:{en:"picture",uk:"зображення"}},
  {w:"Blume",a:"die",l:"A1",t:{en:"flower",uk:"квітка"}},
  {w:"Brief",a:"der",l:"A1",t:{en:"letter",uk:"лист"}},
  {w:"Brot",a:"das",l:"A1",t:{en:"bread",uk:"хліб"}},
  {w:"Buch",a:"das",l:"A1",t:{en:"book",uk:"книга"}},
  {w:"Bus",a:"der",l:"A1",t:{en:"bus",uk:"автобус"}},
  {w:"Butter",a:"die",l:"A1",t:{en:"butter",uk:"масло"}},
  {w:"Computer",a:"der",l:"A1",t:{en:"computer",uk:"комп’ютер"}},
  {w:"Dank",a:"der",l:"A1",t:{en:"thanks",uk:"подяка"}},
  {w:"Dienstag",a:"der",l:"A1",t:{en:"Tuesday",uk:"вівторок"}},
  {w:"Ding",a:"das",l:"A1",t:{en:"thing",uk:"річ"}},
  {w:"Donnerstag",a:"der",l:"A1",t:{en:"Thursday",uk:"четвер"}},
  {w:"Dorf",a:"das",l:"A1",t:{en:"village",uk:"село"}},
  {w:"Durst",a:"der",l:"A1",t:{en:"thirst",uk:"спрага"}},
  {w:"Ei",a:"das",l:"A1",t:{en:"egg",uk:"яйце"}},
  {w:"Eis",a:"das",l:"A1",t:{en:"ice cream",uk:"морозиво"}},
  {w:"Eltern",a:"die",l:"A1",t:{en:"parents",uk:"батьки"}},
  {w:"Familie",a:"die",l:"A1",t:{en:"family",uk:"сімʼя"}},
  {w:"Farbe",a:"die",l:"A1",t:{en:"color",uk:"колір"}},
  {w:"Fahrrad",a:"das",l:"A1",t:{en:"bicycle",uk:"велосипед"}},
  {w:"Fehler",a:"der",l:"A1",t:{en:"mistake",uk:"помилка"}},
  {w:"Fenster",a:"das",l:"A1",t:{en:"window",uk:"вікно"}},
  {w:"Film",a:"der",l:"A1",t:{en:"movie",uk:"фільм"}},
  {w:"Fisch",a:"der",l:"A1",t:{en:"fish",uk:"риба"}},
  {w:"Flasche",a:"die",l:"A1",t:{en:"bottle",uk:"пляшка"}},
  {w:"Fleisch",a:"das",l:"A1",t:{en:"meat",uk:"мʼясо"}},
  {w:"Flughafen",a:"der",l:"A1",t:{en:"airport",uk:"аеропорт"}},
  {w:"Flugzeug",a:"das",l:"A1",t:{en:"airplane",uk:"літак"}},
  {w:"Foto",a:"das",l:"A1",t:{en:"photo",uk:"фото"}},
  {w:"Frage",a:"die",l:"A1",t:{en:"question",uk:"запитання"}},
  {w:"Frau",a:"die",l:"A1",t:{en:"woman",uk:"жінка"}},
  {w:"Freitag",a:"der",l:"A1",t:{en:"Friday",uk:"пʼятниця"}},
  {w:"Freund",a:"der",l:"A1",t:{en:"friend",uk:"друг"}},
  {w:"Frühstück",a:"das",l:"A1",t:{en:"breakfast",uk:"сніданок"}},
  {w:"Fuß",a:"der",l:"A1",t:{en:"foot",uk:"нога"}},
  {w:"Garten",a:"der",l:"A1",t:{en:"garden",uk:"сад"}},
  {w:"Geld",a:"das",l:"A1",t:{en:"money",uk:"гроші"}},
  {w:"Gemüse",a:"das",l:"A1",t:{en:"vegetables",uk:"овочі"}},
  {w:"Geschenk",a:"das",l:"A1",t:{en:"gift",uk:"подарунок"}},
  {w:"Glas",a:"das",l:"A1",t:{en:"glass",uk:"склянка"}},
  {w:"Gott",a:"der",l:"A1",t:{en:"God",uk:"Бог"}},
  {w:"Haar",a:"das",l:"A1",t:{en:"hair",uk:"волосся"}},
  {w:"Hand",a:"die",l:"A1",t:{en:"hand",uk:"рука"}},
  {w:"Haus",a:"das",l:"A1",t:{en:"house",uk:"дім"}},
  {w:"Herr",a:"der",l:"A1",t:{en:"Mr.",uk:"пан"}},
  {w:"Hund",a:"der",l:"A1",t:{en:"dog",uk:"собака"}},
  {w:"Hunger",a:"der",l:"A1",t:{en:"hunger",uk:"голод"}},
  {w:"Hotel",a:"das",l:"A1",t:{en:"hotel",uk:"готель"}},
  {w:"Hut",a:"der",l:"A1",t:{en:"hat",uk:"капелюх"}},
  {w:"Idee",a:"die",l:"A1",t:{en:"idea",uk:"ідея"}},
  {w:"Jacke",a:"die",l:"A1",t:{en:"jacket",uk:"куртка"}},
  {w:"Jahr",a:"das",l:"A1",t:{en:"year",uk:"рік"}},
  {w:"Junge",a:"der",l:"A1",t:{en:"boy",uk:"хлопець"}},
  {w:"Kaffee",a:"der",l:"A1",t:{en:"coffee",uk:"кава"}},
  {w:"Karte",a:"die",l:"A1",t:{en:"card",uk:"картка"}},
  {w:"Katze",a:"die",l:"A1",t:{en:"cat",uk:"кіт"}},
  {w:"Kind",a:"das",l:"A1",t:{en:"child",uk:"дитина"}},
  {w:"Kino",a:"das",l:"A1",t:{en:"cinema",uk:"кінотеатр"}},
  {w:"Klasse",a:"die",l:"A1",t:{en:"class",uk:"клас"}},
  {w:"Kleidung",a:"die",l:"A1",t:{en:"clothes",uk:"одяг"}},
  {w:"Kopf",a:"der",l:"A1",t:{en:"head",uk:"голова"}},
  {w:"Küche",a:"die",l:"A1",t:{en:"kitchen",uk:"кухня"}},
  {w:"Kuchen",a:"der",l:"A1",t:{en:"cake",uk:"пиріг"}},
  {w:"Land",a:"das",l:"A1",t:{en:"country",uk:"країна"}},
  {w:"Lehrer",a:"der",l:"A1",t:{en:"teacher",uk:"вчитель"}},
  {w:"Licht",a:"das",l:"A1",t:{en:"light",uk:"світло"}},
  {w:"Lied",a:"das",l:"A1",t:{en:"song",uk:"пісня"}},
  {w:"Mädchen",a:"das",l:"A1",t:{en:"girl",uk:"дівчина"}},
  {w:"Mann",a:"der",l:"A1",t:{en:"man",uk:"чоловік"}},
  {w:"Mantel",a:"der",l:"A1",t:{en:"coat",uk:"пальто"}},
  {w:"Markt",a:"der",l:"A1",t:{en:"market",uk:"ринок"}},
  {w:"Meer",a:"das",l:"A1",t:{en:"sea",uk:"море"}},
  {w:"Mensch",a:"der",l:"A1",t:{en:"person",uk:"людина"}},
  {w:"Milch",a:"die",l:"A1",t:{en:"milk",uk:"молоко"}},
  {w:"Mittwoch",a:"der",l:"A1",t:{en:"Wednesday",uk:"середа"}},
  {w:"Monat",a:"der",l:"A1",t:{en:"month",uk:"місяць"}},
  {w:"Montag",a:"der",l:"A1",t:{en:"Monday",uk:"понеділок"}},
  {w:"Morgen",a:"der",l:"A1",t:{en:"morning",uk:"ранок"}},
  {w:"Musik",a:"die",l:"A1",t:{en:"music",uk:"музика"}},
  {w:"Mutter",a:"die",l:"A1",t:{en:"mother",uk:"мати"}},
  {w:"Name",a:"der",l:"A1",t:{en:"name",uk:"імʼя"}},
  {w:"Nacht",a:"die",l:"A1",t:{en:"night",uk:"ніч"}},
  {w:"Nummer",a:"die",l:"A1",t:{en:"number",uk:"номер"}},
  {w:"Obst",a:"das",l:"A1",t:{en:"fruit",uk:"фрукти"}},
  {w:"Park",a:"der",l:"A1",t:{en:"park",uk:"парк"}},
  {w:"Party",a:"die",l:"A1",t:{en:"party",uk:"вечірка"}},
  {w:"Platz",a:"der",l:"A1",t:{en:"place",uk:"місце"}},
  {w:"Polizei",a:"die",l:"A1",t:{en:"police",uk:"поліція"}},
  {w:"Preis",a:"der",l:"A1",t:{en:"price",uk:"ціна"}},
  {w:"Problem",a:"das",l:"A1",t:{en:"problem",uk:"проблема"}},
  {w:"Radio",a:"das",l:"A1",t:{en:"radio",uk:"радіо"}},
  {w:"Regen",a:"der",l:"A1",t:{en:"rain",uk:"дощ"}},
  {w:"Restaurant",a:"das",l:"A1",t:{en:"restaurant",uk:"ресторан"}},
  {w:"Salz",a:"das",l:"A1",t:{en:"salt",uk:"сіль"}},
  {w:"Samstag",a:"der",l:"A1",t:{en:"Saturday",uk:"субота"}},
  {w:"Schlüssel",a:"der",l:"A1",t:{en:"key",uk:"ключ"}},
  {w:"Schuh",a:"der",l:"A1",t:{en:"shoe",uk:"взуття"}},
  {w:"Schule",a:"die",l:"A1",t:{en:"school",uk:"школа"}},
  {w:"Schwester",a:"die",l:"A1",t:{en:"sister",uk:"сестра"}},
  {w:"See",a:"der",l:"A1",t:{en:"lake",uk:"озеро"}},
  {w:"Sofa",a:"das",l:"A1",t:{en:"sofa",uk:"диван"}},
  {w:"Sommer",a:"der",l:"A1",t:{en:"summer",uk:"літо"}},
  {w:"Sonne",a:"die",l:"A1",t:{en:"sun",uk:"сонце"}},
  {w:"Sonntag",a:"der",l:"A1",t:{en:"Sunday",uk:"неділя"}},
  {w:"Spaß",a:"der",l:"A1",t:{en:"fun",uk:"задоволення"}},
  {w:"Sport",a:"der",l:"A1",t:{en:"sport",uk:"спорт"}},
  {w:"Sprache",a:"die",l:"A1",t:{en:"language",uk:"мова"}},
  {w:"Stadt",a:"die",l:"A1",t:{en:"city",uk:"місто"}},
  {w:"Straße",a:"die",l:"A1",t:{en:"street",uk:"вулиця"}},
  {w:"Stuhl",a:"der",l:"A1",t:{en:"chair",uk:"стілець"}},
  {w:"Tag",a:"der",l:"A1",t:{en:"day",uk:"день"}},
  {w:"Taxi",a:"das",l:"A1",t:{en:"taxi",uk:"таксі"}},
  {w:"Tee",a:"der",l:"A1",t:{en:"tea",uk:"чай"}},
  {w:"Teppich",a:"der",l:"A1",t:{en:"carpet",uk:"килим"}},
  {w:"Tisch",a:"der",l:"A1",t:{en:"table",uk:"стіл"}},
  {w:"Tochter",a:"die",l:"A1",t:{en:"daughter",uk:"дочка"}},
  {w:"Tür",a:"die",l:"A1",t:{en:"door",uk:"двері"}},
  {w:"Uhr",a:"die",l:"A1",t:{en:"clock",uk:"годинник"}},
  {w:"Vater",a:"der",l:"A1",t:{en:"father",uk:"батько"}},
  {w:"Vogel",a:"der",l:"A1",t:{en:"bird",uk:"птах"}},
  {w:"Wasser",a:"das",l:"A1",t:{en:"water",uk:"вода"}},
  {w:"Weg",a:"der",l:"A1",t:{en:"way",uk:"шлях"}},
  {w:"Wein",a:"der",l:"A1",t:{en:"wine",uk:"вино"}},
  {w:"Welt",a:"die",l:"A1",t:{en:"world",uk:"світ"}},
  {w:"Wetter",a:"das",l:"A1",t:{en:"weather",uk:"погода"}},
  {w:"Woche",a:"die",l:"A1",t:{en:"week",uk:"тиждень"}},
  {w:"Wohnung",a:"die",l:"A1",t:{en:"apartment",uk:"квартира"}},
  {w:"Wort",a:"das",l:"A1",t:{en:"word",uk:"слово"}},
  {w:"Zeit",a:"die",l:"A1",t:{en:"time",uk:"час"}},
  {w:"Zeitung",a:"die",l:"A1",t:{en:"newspaper",uk:"газета"}},
  {w:"Zimmer",a:"das",l:"A1",t:{en:"room",uk:"кімната"}},
  {w:"Zug",a:"der",l:"A1",t:{en:"train",uk:"потяг"}},

// --- LEVEL A2 (Daily Life, Work, Environment) ---
{w:"Abschluss", a:"der", l:"A2", t:{en:"graduation / completion", uk:"закінчення / випуск"}},
{w:"Ahnung", a:"die", l:"A2", t:{en:"idea / clue", uk:"уявлення / поняття"}},
{w:"Ampel", a:"die", l:"A2", t:{en:"traffic light", uk:"світлофор"}},
{w:"Angebot", a:"das", l:"A2", t:{en:"offer", uk:"пропозиція"}},
{w:"Anfang", a:"der", l:"A2", t:{en:"beginning", uk:"початок"}},
{w:"Angst", a:"die", l:"A2", t:{en:"fear", uk:"страх"}},
{w:"Anzug", a:"der", l:"A2", t:{en:"suit", uk:"костюм"}},
{w:"Apotheke", a:"die", l:"A2", t:{en:"pharmacy", uk:"аптека"}},
{w:"Arbeit", a:"die", l:"A2", t:{en:"work / job", uk:"робота"}},
{w:"Ausbildung", a:"die", l:"A2", t:{en:"training / apprenticeship", uk:"професійне навчання"}},
{w:"Ausflug", a:"der", l:"A2", t:{en:"trip / excursion", uk:"поїздка / екскурсія"}},
{w:"Ausgang", a:"der", l:"A2", t:{en:"exit", uk:"вихід"}},
{w:"Ausland", a:"das", l:"A2", t:{en:"abroad / foreign countries", uk:"закордон"}},
{w:"Ausweis", a:"der", l:"A2", t:{en:"ID card", uk:"посвідчення / ID-картка"}},
{w:"Bäckerei", a:"die", l:"A2", t:{en:"bakery", uk:"пекарня"}},
{w:"Balkon", a:"der", l:"A2", t:{en:"balcony", uk:"балкон"}},
{w:"Bekannte", a:"der", l:"A2", t:{en:"acquaintance (male)", uk:"знайомий"}},
{w:"Berg", a:"der", l:"A2", t:{en:"mountain", uk:"гора"}},
{w:"Beruf", a:"der", l:"A2", t:{en:"profession / occupation", uk:"професія"}},
{w:"Besuch", a:"der", l:"A2", t:{en:"visit", uk:"візит"}},
{w:"Bewerbung", a:"die", l:"A2", t:{en:"application", uk:"заява / заявка"}},
{w:"Bier", a:"das", l:"A2", t:{en:"beer", uk:"пиво"}},
{w:"Brille", a:"die", l:"A2", t:{en:"glasses", uk:"окуляри"}},
{w:"Brücke", a:"die", l:"A2", t:{en:"bridge", uk:"міст"}},
{w:"Büro", a:"das", l:"A2", t:{en:"office", uk:"офіс"}},
{w:"Chef", a:"der", l:"A2", t:{en:"boss", uk:"шеф / начальник"}},
{w:"Dach", a:"das", l:"A2", t:{en:"roof", uk:"дах"}},
{w:"Dauer", a:"die", l:"A2", t:{en:"duration", uk:"тривалість"}},
{w:"Drucker", a:"der", l:"A2", t:{en:"printer", uk:"принтер"}},
{w:"Durst", a:"der", l:"A2", t:{en:"thirst", uk:"спрага"}},
{w:"Dusche", a:"die", l:"A2", t:{en:"shower", uk:"душ"}},
{w:"Eingang", a:"der", l:"A2", t:{en:"entrance", uk:"вхід"}},
{w:"Einladung", a:"die", l:"A2", t:{en:"invitation", uk:"запрошення"}},
{w:"Ende", a:"das", l:"A2", t:{en:"end", uk:"кінець"}},
{w:"Erfahrung", a:"die", l:"A2", t:{en:"experience", uk:"досвід"}},
{w:"Ergebnis", a:"das", l:"A2", t:{en:"result", uk:"результат"}},
{w:"Erlaubnis", a:"die", l:"A2", t:{en:"permission", uk:"дозвіл"}},
{w:"Erwachsene", a:"der", l:"A2", t:{en:"adult (male)", uk:"дорослий"}},
{w:"Fahrer", a:"der", l:"A2", t:{en:"driver", uk:"водій"}},
{w:"Fahrkarte", a:"die", l:"A2", t:{en:"ticket", uk:"квиток"}},
{w:"Feier", a:"die", l:"A2", t:{en:"celebration / party", uk:"святкування"}},
{w:"Feuer", a:"das", l:"A2", t:{en:"fire", uk:"вогонь"}},
{w:"Fieber", a:"das", l:"A2", t:{en:"fever", uk:"температура"}},
{w:"Firma", a:"die", l:"A2", t:{en:"company", uk:"фірма / компанія"}},
{w:"Flur", a:"der", l:"A2", t:{en:"hallway", uk:"коридор"}},
{w:"Fluss", a:"der", l:"A2", t:{en:"river", uk:"річка"}},
{w:"Friseur", a:"der", l:"A2", t:{en:"hairdresser", uk:"перукар"}},
{w:"Führerschein", a:"der", l:"A2", t:{en:"driver's license", uk:"водійське посвідчення"}},
{w:"Geburtstag", a:"der", l:"A2", t:{en:"birthday", uk:"день народження"}},
{w:"Gefahr", a:"die", l:"A2", t:{en:"danger", uk:"небезпека"}},
{w:"Gefühl", a:"das", l:"A2", t:{en:"feeling", uk:"почуття"}},
{w:"Gegenteil", a:"das", l:"A2", t:{en:"opposite", uk:"протилежність"}},
{w:"Gehalt", a:"das", l:"A2", t:{en:"salary", uk:"зарплата"}},
{w:"Geschäft", a:"das", l:"A2", t:{en:"shop / business", uk:"магазин / бізнес"}},
{w:"Geschichte", a:"die", l:"A2", t:{en:"story / history", uk:"історія"}},
{w:"Gesicht", a:"das", l:"A2", t:{en:"face", uk:"обличчя"}},
{w:"Gespräch", a:"das", l:"A2", t:{en:"conversation", uk:"розмова"}},
{w:"Gewicht", a:"das", l:"A2", t:{en:"weight", uk:"вага"}},
{w:"Glück", a:"das", l:"A2", t:{en:"luck / happiness", uk:"щастя / удача"}},
{w:"Größe", a:"die", l:"A2", t:{en:"size", uk:"розмір"}},
{w:"Hals", a:"der", l:"A2", t:{en:"neck / throat", uk:"шия / горло"}},
{w:"Hafen", a:"der", l:"A2", t:{en:"harbor / port", uk:"порт"}},
{w:"Hälfte", a:"die", l:"A2", t:{en:"half", uk:"половина"}},
{w:"Handy", a:"das", l:"A2", t:{en:"mobile phone", uk:"мобільний телефон"}},
{w:"Heimat", a:"die", l:"A2", t:{en:"home / homeland", uk:"батьківщина"}},
{w:"Heizung", a:"die", l:"A2", t:{en:"heating", uk:"опалення"}},
{w:"Hemd", a:"das", l:"A2", t:{en:"shirt", uk:"сорочка"}},
{w:"Herd", a:"der", l:"A2", t:{en:"stove", uk:"плита"}},
{w:"Hilfe", a:"die", l:"A2", t:{en:"help", uk:"допомога"}},
{w:"Hobby", a:"das", l:"A2", t:{en:"hobby", uk:"хобі"}},
{w:"Holz", a:"das", l:"A2", t:{en:"wood", uk:"деревина"}},
{w:"Hose", a:"die", l:"A2", t:{en:"pants", uk:"штани"}},
{w:"Hund", a:"der", l:"A2", t:{en:"dog", uk:"собака"}},
{w:"Insel", a:"die", l:"A2", t:{en:"island", uk:"острів"}},
{w:"Instrument", a:"das", l:"A2", t:{en:"instrument", uk:"інструмент"}},
{w:"Internet", a:"das", l:"A2", t:{en:"internet", uk:"інтернет"}},
{w:"Interview", a:"das", l:"A2", t:{en:"interview", uk:"інтерв’ю"}},
{w:"Job", a:"der", l:"A2", t:{en:"job", uk:"робота"}},
{w:"Jugendliche", a:"der", l:"A2", t:{en:"teenager (male)", uk:"підліток"}},
{w:"Kamera", a:"die", l:"A2", t:{en:"camera", uk:"камера"}},
{w:"Karte", a:"die", l:"A2", t:{en:"card / map", uk:"картка / мапа"}},
{w:"Kartoffel", a:"die", l:"A2", t:{en:"potato", uk:"картопля"}},
{w:"Keller", a:"der", l:"A2", t:{en:"cellar / basement", uk:"підвал"}},
{w:"Kiosk", a:"der", l:"A2", t:{en:"kiosk", uk:"кіоск"}},
{w:"Koffer", a:"der", l:"A2", t:{en:"suitcase", uk:"валіза"}},
{w:"Kollege", a:"der", l:"A2", t:{en:"colleague", uk:"колега"}},
{w:"Kontakt", a:"der", l:"A2", t:{en:"contact", uk:"контакт"}},
{w:"Konto", a:"das", l:"A2", t:{en:"account", uk:"рахунок"}},
{w:"Konzert", a:"das", l:"A2", t:{en:"concert", uk:"концерт"}},
{w:"Kosten", a:"die", l:"A2", t:{en:"costs", uk:"витрати"}},
{w:"Kraft", a:"die", l:"A2", t:{en:"strength / power", uk:"сила"}},
{w:"Krankenhaus", a:"das", l:"A2", t:{en:"hospital", uk:"лікарня"}},
{w:"Krankenkasse", a:"die", l:"A2", t:{en:"health insurance", uk:"медична страховка"}},
{w:"Kreditkarte", a:"die", l:"A2", t:{en:"credit card", uk:"кредитна картка"}},
{w:"Kreis", a:"der", l:"A2", t:{en:"circle / district", uk:"коло / район"}},
{w:"Kreuzung", a:"die", l:"A2", t:{en:"intersection", uk:"перехрестя"}},
{w:"Kühlschrank", a:"der", l:"A2", t:{en:"refrigerator", uk:"холодильник"}},
{w:"Kultur", a:"die", l:"A2", t:{en:"culture", uk:"культура"}},
{w:"Kunde", a:"der", l:"A2", t:{en:"customer", uk:"клієнт"}},
{w:"Kurs", a:"der", l:"A2", t:{en:"course", uk:"курс"}},
{w:"Laden", a:"der", l:"A2", t:{en:"shop", uk:"магазин"}},
{w:"Lager", a:"das", l:"A2", t:{en:"warehouse / storage", uk:"склад"}},
{w:"Lampe", a:"die", l:"A2", t:{en:"lamp", uk:"лампа"}},
{w:"Laptop", a:"der", l:"A2", t:{en:"laptop", uk:"ноутбук"}},
{w:"Leben", a:"das", l:"A2", t:{en:"life", uk:"життя"}},
{w:"Leute", a:"die", l:"A2", t:{en:"people", uk:"люди"}},
{w:"Lied", a:"das", l:"A2", t:{en:"song", uk:"пісня"}},
{w:"Loch", a:"das", l:"A2", t:{en:"hole", uk:"дірка"}},
{w:"Löffel", a:"der", l:"A2", t:{en:"spoon", uk:"ложка"}},
{w:"Lohn", a:"der", l:"A2", t:{en:"wage", uk:"зарплата"}},
{w:"Lösung", a:"die", l:"A2", t:{en:"solution", uk:"рішення"}},
{w:"Luft", a:"die", l:"A2", t:{en:"air", uk:"повітря"}},
{w:"Lust", a:"die", l:"A2", t:{en:"desire / mood", uk:"бажання / настрій"}},
{w:"Magen", a:"der", l:"A2", t:{en:"stomach", uk:"шлунок"}},
{w:"Markt", a:"der", l:"A2", t:{en:"market", uk:"ринок"}},
{w:"Maschine", a:"die", l:"A2", t:{en:"machine", uk:"машина"}},
{w:"Material", a:"das", l:"A2", t:{en:"material", uk:"матеріал"}},
{w:"Mechaniker", a:"der", l:"A2", t:{en:"mechanic", uk:"механік"}},
{w:"Medikament", a:"das", l:"A2", t:{en:"medicine", uk:"ліки"}},
{w:"Menge", a:"die", l:"A2", t:{en:"amount", uk:"кількість"}},
{w:"Messer", a:"das", l:"A2", t:{en:"knife", uk:"ніж"}},
{w:"Miete", a:"die", l:"A2", t:{en:"rent", uk:"оренда"}},
{w:"Möbel", a:"die", l:"A2", t:{en:"furniture", uk:"меблі"}},
{w:"Motor", a:"der", l:"A2", t:{en:"engine", uk:"двигун"}},
{w:"Müll", a:"der", l:"A2", t:{en:"trash / garbage", uk:"сміття"}},
{w:"Museum", a:"das", l:"A2", t:{en:"museum", uk:"музей"}},
{w:"Nachbar", a:"der", l:"A2", t:{en:"neighbor", uk:"сусід"}},
{w:"Natur", a:"die", l:"A2", t:{en:"nature", uk:"природа"}},
{w:"Nebel", a:"der", l:"A2", t:{en:"fog", uk:"туман"}},
{w:"Notfall", a:"der", l:"A2", t:{en:"emergency", uk:"надзвичайна ситуація"}},
{w:"Note", a:"die", l:"A2", t:{en:"grade / note", uk:"оцінка / нотатка"}},
{w:"Nudel", a:"die", l:"A2", t:{en:"noodle / pasta", uk:"локшина / макарони"}},


    // --- LEVEL B1 (Society, Abstract, Emotions, Politics) ---
{w:"Abfall", a:"der", l:"B1", t:{en:"waste / garbage", uk:"відходи / сміття"}}, {w:"Abgas", a:"das", l:"B1", t:{en:"exhaust gas", uk:"вихлопний газ"}}, {w:"Absicht", a:"die", l:"B1", t:{en:"intention", uk:"намір"}},
{w:"Abstimmung", a:"die", l:"B1", t:{en:"vote / voting", uk:"голосування"}}, {w:"Altenheim", a:"das", l:"B1", t:{en:"nursing home", uk:"будинок для літніх людей"}}, {w:"Anfang", a:"der", l:"B1", t:{en:"beginning", uk:"початок"}},
{w:"Angestellte", a:"der", l:"B1", t:{en:"employee (male)", uk:"працівник / службовець"}}, {w:"Angst", a:"die", l:"B1", t:{en:"fear", uk:"страх"}}, {w:"Ankunft", a:"die", l:"B1", t:{en:"arrival", uk:"прибуття"}},
{w:"Anlass", a:"der", l:"B1", t:{en:"occasion / reason", uk:"привід / нагода"}}, {w:"Anmeldung", a:"die", l:"B1", t:{en:"registration", uk:"реєстрація"}}, {w:"Anruf", a:"der", l:"B1", t:{en:"phone call", uk:"дзвінок"}},
{w:"Anspruch", a:"der", l:"B1", t:{en:"claim / entitlement", uk:"вимога / право (на щось)"}}, {w:"Anstrengung", a:"die", l:"B1", t:{en:"effort", uk:"зусилля"}}, {w:"Antrag", a:"der", l:"B1", t:{en:"application / request", uk:"заява / клопотання"}},
{w:"Antwort", a:"die", l:"B1", t:{en:"answer", uk:"відповідь"}}, {w:"Anzeige", a:"die", l:"B1", t:{en:"advertisement / report", uk:"оголошення / заява (в поліцію)"}}, {w:"Apotheker", a:"der", l:"B1", t:{en:"pharmacist", uk:"фармацевт"}},
{w:"Apparat", a:"der", l:"B1", t:{en:"device / apparatus", uk:"прилад / апарат"}}, {w:"Arbeitsplatz", a:"der", l:"B1", t:{en:"workplace", uk:"робоче місце"}}, {w:"Architekt", a:"der", l:"B1", t:{en:"architect", uk:"архітектор"}},
{w:"Ärger", a:"der", l:"B1", t:{en:"anger / trouble", uk:"злість / неприємності"}}, {w:"Armut", a:"die", l:"B1", t:{en:"poverty", uk:"бідність"}}, {w:"Art", a:"die", l:"B1", t:{en:"type / kind", uk:"вид / тип"}},
{w:"Artikel", a:"der", l:"B1", t:{en:"article (item / text)", uk:"стаття / товар"}}, {w:"Asyl", a:"das", l:"B1", t:{en:"asylum", uk:"притулок / (політ.) притулок"}}, {w:"Atmosphäre", a:"die", l:"B1", t:{en:"atmosphere", uk:"атмосфера"}},
{w:"Atomkraft", a:"die", l:"B1", t:{en:"nuclear power", uk:"атомна енергетика"}}, {w:"Aufenthalt", a:"der", l:"B1", t:{en:"stay", uk:"перебування"}}, {w:"Aufforderung", a:"die", l:"B1", t:{en:"request / demand", uk:"вимога / прохання"}},
{w:"Aufgabe", a:"die", l:"B1", t:{en:"task", uk:"завдання"}}, {w:"Aufnahme", a:"die", l:"B1", t:{en:"recording / admission", uk:"запис / прийом"}}, {w:"Aufregung", a:"die", l:"B1", t:{en:"excitement / agitation", uk:"хвилювання"}},
{w:"Auftrag", a:"der", l:"B1", t:{en:"assignment / order", uk:"завдання / замовлення"}}, {w:"Augenblick", a:"der", l:"B1", t:{en:"moment", uk:"мить"}}, {w:"Ausbildung", a:"die", l:"B1", t:{en:"training / apprenticeship", uk:"професійне навчання"}},
{w:"Ausdruck", a:"der", l:"B1", t:{en:"expression", uk:"вираз"}}, {w:"Auskunft", a:"die", l:"B1", t:{en:"information", uk:"інформація / довідка"}}, {w:"Ausnahme", a:"die", l:"B1", t:{en:"exception", uk:"виняток"}},
{w:"Ausstellung", a:"die", l:"B1", t:{en:"exhibition", uk:"виставка"}}, {w:"Auswahl", a:"die", l:"B1", t:{en:"selection / choice", uk:"вибір"}}, {w:"Auswirkung", a:"die", l:"B1", t:{en:"effect / impact", uk:"вплив / наслідок"}},
{w:"Auto", a:"das", l:"B1", t:{en:"car", uk:"автомобіль"}}, {w:"Autobahn", a:"die", l:"B1", t:{en:"highway", uk:"автобан"}}, {w:"Automat", a:"der", l:"B1", t:{en:"machine / vending machine", uk:"автомат"}},
{w:"Autor", a:"der", l:"B1", t:{en:"author", uk:"автор"}}, {w:"Backofen", a:"der", l:"B1", t:{en:"oven", uk:"духовка"}}, {w:"Badewanne", a:"die", l:"B1", t:{en:"bathtub", uk:"ванна"}},
{w:"Bahn", a:"die", l:"B1", t:{en:"train / railway", uk:"залізниця / поїзд"}}, {w:"Bahnsteig", a:"der", l:"B1", t:{en:"platform", uk:"перон"}}, {w:"Baustelle", a:"die", l:"B1", t:{en:"construction site", uk:"будівельний майданчик"}},
{w:"Beamte", a:"der", l:"B1", t:{en:"civil servant (male)", uk:"держслужбовець / чиновник"}}, {w:"Bedarf", a:"der", l:"B1", t:{en:"need / demand", uk:"потреба"}}, {w:"Bedienung", a:"die", l:"B1", t:{en:"service / waitress", uk:"обслуговування / офіціантка"}},
{w:"Bedingung", a:"die", l:"B1", t:{en:"condition", uk:"умова"}}, {w:"Bedürfnis", a:"das", l:"B1", t:{en:"need / necessity", uk:"потреба"}}, {w:"Befehl", a:"der", l:"B1", t:{en:"command / order", uk:"наказ"}},
{w:"Begegnung", a:"die", l:"B1", t:{en:"encounter", uk:"зустріч"}}, {w:"Beginn", a:"der", l:"B1", t:{en:"start / beginning", uk:"початок"}}, {w:"Begründung", a:"die", l:"B1", t:{en:"reason / justification", uk:"обґрунтування"}},
{w:"Behörde", a:"die", l:"B1", t:{en:"authority / agency", uk:"установа / відомство"}}, {w:"Bein", a:"das", l:"B1", t:{en:"leg", uk:"нога"}}, {w:"Beispiel", a:"das", l:"B1", t:{en:"example", uk:"приклад"}},
{w:"Beitrag", a:"der", l:"B1", t:{en:"contribution / fee", uk:"внесок / внесення"}}, {w:"Bekannte", a:"der", l:"B1", t:{en:"acquaintance (male)", uk:"знайомий"}}, {w:"Beleg", a:"der", l:"B1", t:{en:"receipt / proof", uk:"квитанція / доказ"}},
{w:"Belohnung", a:"die", l:"B1", t:{en:"reward", uk:"нагорода"}}, {w:"Bemühung", a:"die", l:"B1", t:{en:"effort", uk:"зусилля"}}, {w:"Benzin", a:"das", l:"B1", t:{en:"gasoline", uk:"бензин"}},
{w:"Beratung", a:"die", l:"B1", t:{en:"consultation / advice", uk:"консультація"}}, {w:"Bereich", a:"der", l:"B1", t:{en:"area / field", uk:"сфера / область"}}, {w:"Bereitschaft", a:"die", l:"B1", t:{en:"willingness / readiness", uk:"готовність"}},
{w:"Bericht", a:"der", l:"B1", t:{en:"report", uk:"звіт"}}, {w:"Beschluss", a:"der", l:"B1", t:{en:"decision / resolution", uk:"рішення / постанова"}}, {w:"Beschwerde", a:"die", l:"B1", t:{en:"complaint", uk:"скарга"}},
{w:"Besitz", a:"der", l:"B1", t:{en:"property / possession", uk:"власність / майно"}}, {w:"Besonderheit", a:"die", l:"B1", t:{en:"special feature", uk:"особливість"}}, {w:"Bestätigung", a:"die", l:"B1", t:{en:"confirmation", uk:"підтвердження"}},
{w:"Bestellung", a:"die", l:"B1", t:{en:"order", uk:"замовлення"}}, {w:"Besuch", a:"der", l:"B1", t:{en:"visit", uk:"візит"}}, {w:"Betrieb", a:"der", l:"B1", t:{en:"operation / company", uk:"підприємство / робота (процес)"}},
{w:"Betrug", a:"der", l:"B1", t:{en:"fraud", uk:"шахрайство"}}, {w:"Bett", a:"das", l:"B1", t:{en:"bed", uk:"ліжко"}}, {w:"Bevölkerung", a:"die", l:"B1", t:{en:"population", uk:"населення"}},
{w:"Bewegung", a:"die", l:"B1", t:{en:"movement", uk:"рух"}}, {w:"Beweis", a:"der", l:"B1", t:{en:"proof / evidence", uk:"доказ"}}, {w:"Bewerber", a:"der", l:"B1", t:{en:"applicant (male)", uk:"кандидат / заявник"}},
{w:"Beziehung", a:"die", l:"B1", t:{en:"relationship", uk:"стосунки"}}, {w:"Bibliothek", a:"die", l:"B1", t:{en:"library", uk:"бібліотека"}}, {w:"Bildschirm", a:"der", l:"B1", t:{en:"screen / monitor", uk:"екран / монітор"}},
{w:"Bildung", a:"die", l:"B1", t:{en:"education", uk:"освіта"}}, {w:"Biografie", a:"die", l:"B1", t:{en:"biography", uk:"біографія"}}, {w:"Biologie", a:"die", l:"B1", t:{en:"biology", uk:"біологія"}},
{w:"Birne", a:"die", l:"B1", t:{en:"pear", uk:"груша"}}, {w:"Bitte", a:"die", l:"B1", t:{en:"request", uk:"прохання"}}, {w:"Blatt", a:"das", l:"B1", t:{en:"leaf / sheet", uk:"листок / аркуш"}},
{w:"Bleistift", a:"der", l:"B1", t:{en:"pencil", uk:"олівець"}}, {w:"Blick", a:"der", l:"B1", t:{en:"look / glance", uk:"погляд"}}, {w:"Blitz", a:"der", l:"B1", t:{en:"lightning / flash", uk:"блискавка / спалах"}},
{w:"Blut", a:"das", l:"B1", t:{en:"blood", uk:"кров"}}, {w:"Boden", a:"der", l:"B1", t:{en:"floor / ground / soil", uk:"підлога / ґрунт"}}, {w:"Bombe", a:"die", l:"B1", t:{en:"bomb", uk:"бомба"}},
{w:"Boot", a:"das", l:"B1", t:{en:"boat", uk:"човен"}}, {w:"Botschaft", a:"die", l:"B1", t:{en:"message / embassy", uk:"повідомлення / посольство"}}, {w:"Brand", a:"der", l:"B1", t:{en:"fire", uk:"пожежа"}},
{w:"Braten", a:"der", l:"B1", t:{en:"roast", uk:"печеня"}}, {w:"Brauch", a:"der", l:"B1", t:{en:"custom / tradition", uk:"звичай"}}, {w:"Briefkasten", a:"der", l:"B1", t:{en:"mailbox", uk:"поштова скринька"}},
{w:"Briefmarke", a:"die", l:"B1", t:{en:"stamp", uk:"поштова марка"}}, {w:"Brieftasche", a:"die", l:"B1", t:{en:"wallet", uk:"гаманець"}}, {w:"Brille", a:"die", l:"B1", t:{en:"glasses", uk:"окуляри"}},
{w:"Broschüre", a:"die", l:"B1", t:{en:"brochure", uk:"брошура"}}, {w:"Brunnen", a:"der", l:"B1", t:{en:"fountain / well", uk:"фонтан / криниця"}}, {w:"Brust", a:"die", l:"B1", t:{en:"chest / breast", uk:"груди"}},
{w:"Buchstabe", a:"der", l:"B1", t:{en:"letter (alphabet)", uk:"літера"}}, {w:"Bühne", a:"die", l:"B1", t:{en:"stage", uk:"сцена"}}, {w:"Bund", a:"der", l:"B1", t:{en:"federation", uk:"федерація / союз"}},
{w:"Bundeskanzler", a:"der", l:"B1", t:{en:"federal chancellor", uk:"федеральний канцлер"}}, {w:"Bürger", a:"der", l:"B1", t:{en:"citizen", uk:"громадянин"}}, {w:"Bürgermeister", a:"der", l:"B1", t:{en:"mayor", uk:"мер"}},


// --- LEVEL B2 (Professional, Academic, Complex) ---
{w:"Abhängigkeit", a:"die", l:"B2", t:{en:"dependence", uk:"залежність"}},
{w:"Abkommen", a:"das", l:"B2", t:{en:"agreement", uk:"угода"}},
{w:"Absatz", a:"der", l:"B2", t:{en:"paragraph / sales", uk:"абзац / збут"}},
{w:"Abschnitt", a:"der", l:"B2", t:{en:"section", uk:"розділ"}},
{w:"Abwechslung", a:"die", l:"B2", t:{en:"variety", uk:"різноманітність"}},
{w:"Abwesenheit", a:"die", l:"B2", t:{en:"absence", uk:"відсутність"}},
{w:"Aktion", a:"die", l:"B2", t:{en:"action", uk:"дія"}},
{w:"Alternative", a:"die", l:"B2", t:{en:"alternative", uk:"альтернатива"}},
{w:"Amt", a:"das", l:"B2", t:{en:"office / authority", uk:"установа"}},
{w:"Analyse", a:"die", l:"B2", t:{en:"analysis", uk:"аналіз"}},
{w:"Anforderung", a:"die", l:"B2", t:{en:"requirement", uk:"вимога"}},
{w:"Angehörige", a:"der", l:"B2", t:{en:"relative", uk:"родич"}},
{w:"Angelegenheit", a:"die", l:"B2", t:{en:"matter / issue", uk:"справа"}},
{w:"Angriff", a:"der", l:"B2", t:{en:"attack", uk:"напад"}},
{w:"Anlage", a:"die", l:"B2", t:{en:"investment / facility", uk:"інвестиція / установка"}},
{w:"Anleitung", a:"die", l:"B2", t:{en:"instruction", uk:"інструкція"}},
{w:"Annahme", a:"die", l:"B2", t:{en:"assumption", uk:"припущення"}},
{w:"Anpassung", a:"die", l:"B2", t:{en:"adjustment", uk:"адаптація"}},
{w:"Anschluss", a:"der", l:"B2", t:{en:"connection", uk:"підключення"}},
{w:"Ansehen", a:"das", l:"B2", t:{en:"reputation", uk:"репутація"}},
{w:"Ansicht", a:"die", l:"B2", t:{en:"view / opinion", uk:"погляд"}},
{w:"Anspruch", a:"der", l:"B2", t:{en:"claim / entitlement", uk:"право / вимога"}},
{w:"Anteil", a:"der", l:"B2", t:{en:"share", uk:"частка"}},
{w:"Anwendung", a:"die", l:"B2", t:{en:"application", uk:"застосування"}},
{w:"Anwesenheit", a:"die", l:"B2", t:{en:"presence", uk:"присутність"}},
{w:"Anzahl", a:"die", l:"B2", t:{en:"number", uk:"кількість"}},
{w:"Argument", a:"das", l:"B2", t:{en:"argument", uk:"аргумент"}},
{w:"Armut", a:"die", l:"B2", t:{en:"poverty", uk:"бідність"}},
{w:"Aspekt", a:"der", l:"B2", t:{en:"aspect", uk:"аспект"}},
{w:"Auffassung", a:"die", l:"B2", t:{en:"opinion", uk:"точка зору"}},
{w:"Aufmerksamkeit", a:"die", l:"B2", t:{en:"attention", uk:"увага"}},
{w:"Aufnahme", a:"die", l:"B2", t:{en:"admission / recording", uk:"прийом / запис"}},
{w:"Auftritt", a:"der", l:"B2", t:{en:"appearance", uk:"виступ"}},
{w:"Aufwand", a:"der", l:"B2", t:{en:"effort", uk:"зусилля"}},
{w:"Ausdruck", a:"der", l:"B2", t:{en:"expression", uk:"вираз"}},
{w:"Auseinandersetzung", a:"die", l:"B2", t:{en:"dispute", uk:"конфлікт"}},
{w:"Ausgabe", a:"die", l:"B2", t:{en:"expense / edition", uk:"витрати / випуск"}},
{w:"Ausgleich", a:"der", l:"B2", t:{en:"balance / compensation", uk:"компенсація"}},
{w:"Aussage", a:"die", l:"B2", t:{en:"statement", uk:"заява"}},
{w:"Aussicht", a:"die", l:"B2", t:{en:"prospect", uk:"перспектива"}},
{w:"Austausch", a:"der", l:"B2", t:{en:"exchange", uk:"обмін"}},
{w:"Auswahl", a:"die", l:"B2", t:{en:"selection", uk:"вибір"}},
{w:"Auswirkung", a:"die", l:"B2", t:{en:"effect", uk:"вплив"}},
{w:"Band", a:"das", l:"B2", t:{en:"volume / band", uk:"том / гурт"}},
{w:"Basis", a:"die", l:"B2", t:{en:"basis", uk:"основа"}},
{w:"Bau", a:"der", l:"B2", t:{en:"construction", uk:"будівництво"}},
{w:"Bedeutung", a:"die", l:"B2", t:{en:"meaning", uk:"значення"}},
{w:"Bedrohung", a:"die", l:"B2", t:{en:"threat", uk:"загроза"}},
{w:"Begeisterung", a:"die", l:"B2", t:{en:"enthusiasm", uk:"захоплення"}},
{w:"Begriff", a:"der", l:"B2", t:{en:"concept", uk:"поняття"}},
{w:"Behandlung", a:"die", l:"B2", t:{en:"treatment", uk:"лікування"}},
{w:"Behauptung", a:"die", l:"B2", t:{en:"claim", uk:"твердження"}},
{w:"Behörde", a:"die", l:"B2", t:{en:"authority", uk:"орган влади"}},
{w:"Beitrag", a:"der", l:"B2", t:{en:"contribution", uk:"внесок"}},
{w:"Belastung", a:"die", l:"B2", t:{en:"burden", uk:"навантаження"}},
{w:"Beobachtung", a:"die", l:"B2", t:{en:"observation", uk:"спостереження"}},
{w:"Beratung", a:"die", l:"B2", t:{en:"consultation", uk:"консультація"}},
{w:"Bereich", a:"der", l:"B2", t:{en:"area / field", uk:"сфера"}},
{w:"Bereitschaft", a:"die", l:"B2", t:{en:"willingness", uk:"готовність"}},
{w:"Bericht", a:"der", l:"B2", t:{en:"report", uk:"звіт"}},
{w:"Berücksichtigung", a:"die", l:"B2", t:{en:"consideration", uk:"урахування"}},
{w:"Beschäftigung", a:"die", l:"B2", t:{en:"employment", uk:"зайнятість"}},
{w:"Beschreibung", a:"die", l:"B2", t:{en:"description", uk:"опис"}},
{w:"Beschwerde", a:"die", l:"B2", t:{en:"complaint", uk:"скарга"}},
{w:"Bestandteil", a:"der", l:"B2", t:{en:"component", uk:"складова"}},
{w:"Bestätigung", a:"die", l:"B2", t:{en:"confirmation", uk:"підтвердження"}},
{w:"Beteiligung", a:"die", l:"B2", t:{en:"participation", uk:"участь"}},
{w:"Betrachtung", a:"die", l:"B2", t:{en:"consideration", uk:"розгляд"}},
{w:"Betrag", a:"der", l:"B2", t:{en:"amount", uk:"сума"}},
{w:"Betreuung", a:"die", l:"B2", t:{en:"care / support", uk:"підтримка"}},
{w:"Beurteilung", a:"die", l:"B2", t:{en:"assessment", uk:"оцінка"}},
{w:"Bevölkerung", a:"die", l:"B2", t:{en:"population", uk:"населення"}},
{w:"Bewegung", a:"die", l:"B2", t:{en:"movement", uk:"рух"}},
{w:"Beweis", a:"der", l:"B2", t:{en:"proof", uk:"доказ"}},
{w:"Bewertung", a:"die", l:"B2", t:{en:"evaluation", uk:"оцінювання"}},
{w:"Bewusstsein", a:"das", l:"B2", t:{en:"awareness", uk:"свідомість"}},
{w:"Beziehung", a:"die", l:"B2", t:{en:"relationship", uk:"відносини"}},
{w:"Bezirk", a:"der", l:"B2", t:{en:"district", uk:"район"}},
{w:"Bilanz", a:"die", l:"B2", t:{en:"balance sheet", uk:"баланс"}},
{w:"Bildung", a:"die", l:"B2", t:{en:"education", uk:"освіта"}},
{w:"Bindung", a:"die", l:"B2", t:{en:"bond", uk:"звʼязок"}},
{w:"Blick", a:"der", l:"B2", t:{en:"glance", uk:"погляд"}},
{w:"Botschaft", a:"die", l:"B2", t:{en:"message", uk:"повідомлення"}},
{w:"Branche", a:"die", l:"B2", t:{en:"industry", uk:"галузь"}},
{w:"Budget", a:"das", l:"B2", t:{en:"budget", uk:"бюджет"}},
{w:"Bündnis", a:"das", l:"B2", t:{en:"alliance", uk:"союз"}},
{w:"Bürger", a:"der", l:"B2", t:{en:"citizen", uk:"громадянин"}},
{w:"Charakter", a:"der", l:"B2", t:{en:"character", uk:"характер"}},
{w:"Chance", a:"die", l:"B2", t:{en:"chance", uk:"шанс"}},
{w:"Chaos", a:"das", l:"B2", t:{en:"chaos", uk:"хаос"}},
{w:"Computer", a:"der", l:"B2", t:{en:"computer", uk:"компʼютер"}},
{w:"Dank", a:"der", l:"B2", t:{en:"thanks", uk:"подяка"}},
{w:"Darstellung", a:"die", l:"B2", t:{en:"presentation", uk:"представлення"}},
{w:"Dauer", a:"die", l:"B2", t:{en:"duration", uk:"тривалість"}},
{w:"Debatte", a:"die", l:"B2", t:{en:"debate", uk:"дебати"}},
{w:"Deckung", a:"die", l:"B2", t:{en:"coverage", uk:"покриття"}},
{w:"Defizit", a:"das", l:"B2", t:{en:"deficit", uk:"дефіцит"}},
{w:"Definition", a:"die", l:"B2", t:{en:"definition", uk:"визначення"}},
{w:"Demokratie", a:"die", l:"B2", t:{en:"democracy", uk:"демократія"}},
{w:"Denken", a:"das", l:"B2", t:{en:"thinking", uk:"мислення"}},
{w:"Detail", a:"das", l:"B2", t:{en:"detail", uk:"деталь"}},
{w:"Diagnose", a:"die", l:"B2", t:{en:"diagnosis", uk:"діагноз"}},
{w:"Dialog", a:"der", l:"B2", t:{en:"dialogue", uk:"діалог"}},
{w:"Differenz", a:"die", l:"B2", t:{en:"difference", uk:"різниця"}},
{w:"Dimension", a:"die", l:"B2", t:{en:"dimension", uk:"вимір"}},
{w:"Diskussion", a:"die", l:"B2", t:{en:"discussion", uk:"обговорення"}},
{w:"Distanz", a:"die", l:"B2", t:{en:"distance", uk:"дистанція"}},
{w:"Dokument", a:"das", l:"B2", t:{en:"document", uk:"документ"}},
{w:"Dosis", a:"die", l:"B2", t:{en:"dose", uk:"доза"}},
{w:"Druck", a:"der", l:"B2", t:{en:"pressure", uk:"тиск"}},
{w:"Durchschnitt", a:"der", l:"B2", t:{en:"average", uk:"середній"}}

];
