const rawDataA1 = [
  // --- LEVEL A1 (The Basics) ---
  {w:"Abend",a:"der",l:"A1",t:{en:"evening",uk:"вечір"}},
  {w:"Adresse",a:"die",l:"A1",t:{en:"address",uk:"адреса"}},
  {w:"Alter",a:"das",l:"A1",t:{en:"age",uk:"вік"}},
  {w:"Antwort",a:"die",l:"A1",t:{en:"answer",uk:"відповідь"}},
  {w:"Apfel",a:"der",l:"A1",t:{en:"apple",uk:"яблуко"}},
  {w:"Apotheke",a:"die",l:"A1",t:{en:"pharmacy",uk:"аптека"}},
  {w:"Arbeit",a:"die",l:"A1",t:{en:"work",uk:"робота"}},
  {w:"Arzt",a:"der",l:"A1",t:{en:"doctor",uk:"лікар"}},
  {w:"Auge",a:"das",l:"A1",t:{en:"eye",uk:"око"}},
  {w:"August",a:"der",l:"A1",t:{en:"August",uk:"серпень"}},
  {w:"Ausbildung",a:"die",l:"A1",t:{en:"education",uk:"освіта"}},
  {w:"Ausflug",a:"der",l:"A1",t:{en:"excursion",uk:"екскурсія"}},
  {w:"Ausgang",a:"der",l:"A1",t:{en:"exit",uk:"вихід"}},
  {w:"Auto",a:"das",l:"A1",t:{en:"car",uk:"автомобіль"}},
  {w:"Baby",a:"das",l:"A1",t:{en:"baby",uk:"дитина"}},
  {w:"Bäckerei",a:"die",l:"A1",t:{en:"bakery",uk:"пекарня"}},
  {w:"Bad",a:"das",l:"A1",t:{en:"bath",uk:"ванна"}},
  {w:"Bahnhof",a:"der",l:"A1",t:{en:"train station",uk:"вокзал"}},
  {w:"Bahnsteig",a:"der",l:"A1",t:{en:"platform",uk:"перон"}},
  {w:"Balkon",a:"der",l:"A1",t:{en:"balcony",uk:"балкон"}},
  {w:"Banane",a:"die",l:"A1",t:{en:"banana",uk:"банан"}},
  {w:"Bauch",a:"der",l:"A1",t:{en:"stomach",uk:"живіт"}},
  {w:"Baum",a:"der",l:"A1",t:{en:"tree",uk:"дерево"}},
  {w:"Bein",a:"das",l:"A1",t:{en:"leg",uk:"нога"}},
  {w:"Beispiel",a:"das",l:"A1",t:{en:"example",uk:"приклад"}},
  {w:"Beruf",a:"der",l:"A1",t:{en:"profession",uk:"професія"}},
  {w:"Bett",a:"das",l:"A1",t:{en:"bed",uk:"ліжко"}},
  {w:"Bier",a:"das",l:"A1",t:{en:"beer",uk:"пиво"}},
  {w:"Bild",a:"das",l:"A1",t:{en:"picture",uk:"картина"}},
  {w:"Bildschirm",a:"der",l:"A1",t:{en:"screen",uk:"екран"}},
  {w:"Birne",a:"die",l:"A1",t:{en:"pear",uk:"груша"}},
  {w:"Bitte",a:"die",l:"A1",t:{en:"request",uk:"прохання"}},
  {w:"Blatt",a:"das",l:"A1",t:{en:"leaf",uk:"листок"}},
  {w:"Bleistift",a:"der",l:"A1",t:{en:"pencil",uk:"олівець"}},
  {w:"Blume",a:"die",l:"A1",t:{en:"flower",uk:"квітка"}},
  {w:"Bluse",a:"die",l:"A1",t:{en:"blouse",uk:"блузка"}},
  {w:"Boden",a:"der",l:"A1",t:{en:"floor",uk:"підлога"}},
  {w:"Brief",a:"der",l:"A1",t:{en:"letter",uk:"лист"}},
  {w:"Brot",a:"das",l:"A1",t:{en:"bread",uk:"хліб"}},
  {w:"Brötchen",a:"das",l:"A1",t:{en:"bread roll",uk:"булочка"}},
  {w:"Bruder",a:"der",l:"A1",t:{en:"brother",uk:"брат"}},
  {w:"Buch",a:"das",l:"A1",t:{en:"book",uk:"книга"}},
  {w:"Buchstabe",a:"der",l:"A1",t:{en:"letter",uk:"літера"}},
  {w:"Bus",a:"der",l:"A1",t:{en:"bus",uk:"автобус"}},
  {w:"Butter",a:"die",l:"A1",t:{en:"butter",uk:"масло"}},
  {w:"Café",a:"das",l:"A1",t:{en:"cafe",uk:"кафе"}},
  {w:"Chance",a:"die",l:"A1",t:{en:"chance",uk:"шанс"}},
  {w:"Chef",a:"der",l:"A1",t:{en:"boss",uk:"шеф"}},
  {w:"Computer",a:"der",l:"A1",t:{en:"computer",uk:"комп'ютер"}},
  {w:"Dank",a:"der",l:"A1",t:{en:"thanks",uk:"подяка"}},
  {w:"Datum",a:"das",l:"A1",t:{en:"date",uk:"дата"}},
  {w:"Dienstag",a:"der",l:"A1",t:{en:"Tuesday",uk:"вівторок"}},
  {w:"Ding",a:"das",l:"A1",t:{en:"thing",uk:"річ"}},
  {w:"Donnerstag",a:"der",l:"A1",t:{en:"Thursday",uk:"четвер"}},
  {w:"Dorf",a:"das",l:"A1",t:{en:"village",uk:"село"}},
  {w:"Drucker",a:"der",l:"A1",t:{en:"printer",uk:"принтер"}},
  {w:"Durst",a:"der",l:"A1",t:{en:"thirst",uk:"спрага"}},
  {w:"Ei",a:"das",l:"A1",t:{en:"egg",uk:"яйце"}},
  {w:"Eingang",a:"der",l:"A1",t:{en:"entrance",uk:"вхід"}},
  {w:"Einladung",a:"die",l:"A1",t:{en:"invitation",uk:"запрошення"}},
  {w:"Eis",a:"das",l:"A1",t:{en:"ice",uk:"лід/морозиво"}},
  {w:"Eltern",a:"die",l:"A1",t:{en:"parents",uk:"батьки"}},
  {w:"Ende",a:"das",l:"A1",t:{en:"end",uk:"кінець"}},
  {w:"Entschuldigung",a:"die",l:"A1",t:{en:"excuse",uk:"вибачення"}},
  {w:"Essen",a:"das",l:"A1",t:{en:"food",uk:"їжа"}},
  {w:"Euro",a:"der",l:"A1",t:{en:"euro",uk:"євро"}},
  {w:"Fahrrad",a:"das",l:"A1",t:{en:"bicycle",uk:"велосипед"}},
  {w:"Familie",a:"die",l:"A1",t:{en:"family",uk:"сім'я"}},
  {w:"Farbe",a:"die",l:"A1",t:{en:"color",uk:"колір"}},
  {w:"Februar",a:"der",l:"A1",t:{en:"February",uk:"лютий"}},
  {w:"Fehler",a:"der",l:"A1",t:{en:"mistake",uk:"помилка"}},
  {w:"Fenster",a:"das",l:"A1",t:{en:"window",uk:"вікно"}},
  {w:"Ferien",a:"die",l:"A1",t:{en:"vacation",uk:"канікули"}},
  {w:"Fernseher",a:"der",l:"A1",t:{en:"TV",uk:"телевізор"}},
  {w:"Fest",a:"das",l:"A1",t:{en:"festival",uk:"свято"}},
  {w:"Feuer",a:"das",l:"A1",t:{en:"fire",uk:"вогонь"}},
  {w:"Fieber",a:"das",l:"A1",t:{en:"fever",uk:"температура"}},
  {w:"Film",a:"der",l:"A1",t:{en:"movie",uk:"фільм"}},
  {w:"Finger",a:"der",l:"A1",t:{en:"finger",uk:"палець"}},
  {w:"Fisch",a:"der",l:"A1",t:{en:"fish",uk:"риба"}},
  {w:"Flasche",a:"die",l:"A1",t:{en:"bottle",uk:"пляшка"}},
  {w:"Fleisch",a:"das",l:"A1",t:{en:"meat",uk:"м'ясо"}},
  {w:"Flughafen",a:"der",l:"A1",t:{en:"airport",uk:"аеропорт"}},
  {w:"Flugzeug",a:"das",l:"A1",t:{en:"airplane",uk:"літак"}},
  {w:"Flur",a:"der",l:"A1",t:{en:"hallway",uk:"коридор"}},
  {w:"Formular",a:"das",l:"A1",t:{en:"form",uk:"формуляр"}},
  {w:"Foto",a:"das",l:"A1",t:{en:"photo",uk:"фотографія"}},
  {w:"Frage",a:"die",l:"A1",t:{en:"question",uk:"питання"}},
  {w:"Frau",a:"die",l:"A1",t:{en:"woman",uk:"жінка"}},
  {w:"Freitag",a:"der",l:"A1",t:{en:"Friday",uk:"п'ятниця"}},
  {w:"Freizeit",a:"die",l:"A1",t:{en:"free time",uk:"дозвілля"}},
  {w:"Freund",a:"der",l:"A1",t:{en:"friend",uk:"друг"}},
  {w:"Frühstück",a:"das",l:"A1",t:{en:"breakfast",uk:"сніданок"}},
  {w:"Fuß",a:"der",l:"A1",t:{en:"foot",uk:"стопа"}},
  {w:"Fußball",a:"der",l:"A1",t:{en:"football",uk:"футбол"}},
  {w:"Gabel",a:"die",l:"A1",t:{en:"fork",uk:"виделка"}},
  {w:"Garage",a:"die",l:"A1",t:{en:"garage",uk:"гараж"}},
  {w:"Garten",a:"der",l:"A1",t:{en:"garden",uk:"сад"}},
  {w:"Gast",a:"der",l:"A1",t:{en:"guest",uk:"гість"}},
  {w:"Gebühr",a:"die",l:"A1",t:{en:"fee",uk:"збір"}},
  {w:"Geld",a:"das",l:"A1",t:{en:"money",uk:"гроші"}},
  {w:"Gemüse",a:"das",l:"A1",t:{en:"vegetables",uk:"овочі"}},
  {w:"Gepäck",a:"das",l:"A1",t:{en:"luggage",uk:"багаж"}},
  {w:"Gericht",a:"das",l:"A1",t:{en:"dish",uk:"страва"}},
  {w:"Geschenk",a:"das",l:"A1",t:{en:"gift",uk:"подарунок"}},
  {w:"Geschirr",a:"das",l:"A1",t:{en:"dishes",uk:"посуд"}},
  {w:"Gesicht",a:"das",l:"A1",t:{en:"face",uk:"обличчя"}},
  {w:"Getränk",a:"das",l:"A1",t:{en:"drink",uk:"напій"}},
  {w:"Glas",a:"das",l:"A1",t:{en:"glass",uk:"склянка"}},
  {w:"Gleis",a:"das",l:"A1",t:{en:"track",uk:"колія"}},
  {w:"Glück",a:"das",l:"A1",t:{en:"luck",uk:"щастя"}},
  {w:"Gott",a:"der",l:"A1",t:{en:"god",uk:"бог"}},
  {w:"Grad",a:"der",l:"A1",t:{en:"degree",uk:"градус"}},
  {w:"Gramm",a:"das",l:"A1",t:{en:"gram",uk:"грам"}},
  {w:"Größe",a:"die",l:"A1",t:{en:"size",uk:"розмір"}},
  {w:"Gruppe",a:"die",l:"A1",t:{en:"group",uk:"група"}},
  {w:"Gruß",a:"der",l:"A1",t:{en:"greeting",uk:"привіт"}},
  {w:"Haar",a:"das",l:"A1",t:{en:"hair",uk:"волосся"}},
  {w:"Hals",a:"der",l:"A1",t:{en:"neck",uk:"шия/горло"}},
  {w:"Haltestelle",a:"die",l:"A1",t:{en:"stop",uk:"зупинка"}},
  {w:"Hand",a:"die",l:"A1",t:{en:"hand",uk:"рука"}},
  {w:"Handy",a:"das",l:"A1",t:{en:"mobile phone",uk:"мобільний телефон"}},
  {w:"Haus",a:"das",l:"A1",t:{en:"house",uk:"будинок"}},
  {w:"Heimat",a:"die",l:"A1",t:{en:"homeland",uk:"батьківщина"}},
  {w:"Heizung", a:"die", l:"A1", t:{en:"heating", uk:"опалення"}},
  {w:"Hemd", a:"das", l:"A1", t:{en:"shirt", uk:"сорочка"}},
  {w:"Herr", a:"der", l:"A1", t:{en:"gentleman", uk:"пан"}},
  {w:"Hilfe", a:"die", l:"A1", t:{en:"help", uk:"допомога"}},
  {w:"Hobby", a:"das", l:"A1", t:{en:"hobby", uk:"хобі"}},
  {w:"Hotel", a:"das", l:"A1", t:{en:"hotel", uk:"готель"}},
  {w:"Hund", a:"der", l:"A1", t:{en:"dog", uk:"собака"}},
  {w:"Hunger", a:"der", l:"A1", t:{en:"hunger", uk:"голод"}},
  {w:"Idee", a:"die", l:"A1", t:{en:"idea", uk:"ідея"}},
  {w:"Inhalt", a:"der", l:"A1", t:{en:"content", uk:"зміст"}},
  {w:"Insel", a:"die", l:"A1", t:{en:"island", uk:"острів"}},
  {w:"Internet", a:"das", l:"A1", t:{en:"internet", uk:"інтернет"}},
  {w:"Jacke", a:"die", l:"A1", t:{en:"jacket", uk:"куртка"}},
  {w:"Jahr", a:"das", l:"A1", t:{en:"year", uk:"рік"}},
  {w:"Januar", a:"der", l:"A1", t:{en:"January", uk:"січень"}},
  {w:"Job", a:"der", l:"A1", t:{en:"job", uk:"робота"}},
  {w:"Junge", a:"der", l:"A1", t:{en:"boy", uk:"хлопець"}},
  {w:"Kaffee", a:"der", l:"A1", t:{en:"coffee", uk:"кава"}},
  {w:"Kalender", a:"der", l:"A1", t:{en:"calendar", uk:"календар"}},
  {w:"Kamera", a:"die", l:"A1", t:{en:"camera", uk:"камера"}},
  {w:"Karte", a:"die", l:"A1", t:{en:"card/map", uk:"картка/карта"}},
  {w:"Kartoffel", a:"die", l:"A1", t:{en:"potato", uk:"картопля"}},
  {w:"Käse", a:"der", l:"A1", t:{en:"cheese", uk:"сир"}},
  {w:"Kasse", a:"die", l:"A1", t:{en:"cash register", uk:"каса"}},
  {w:"Katze", a:"die", l:"A1", t:{en:"cat", uk:"кішка"}},
  {w:"Keller", a:"der", l:"A1", t:{en:"cellar", uk:"підвал"}},
  {w:"Kette", a:"die", l:"A1", t:{en:"chain", uk:"ланцюжок"}},
  {w:"Kind", a:"das", l:"A1", t:{en:"child", uk:"дитина"}},
  {w:"Kino", a:"das", l:"A1", t:{en:"cinema", uk:"кінотеатр"}},
  {w:"Kiosk", a:"der", l:"A1", t:{en:"kiosk", uk:"кіоск"}},
  {w:"Kirche", a:"die", l:"A1", t:{en:"church", uk:"церква"}},
  {w:"Klasse", a:"die", l:"A1", t:{en:"class", uk:"клас"}},
  {w:"Kleid", a:"das", l:"A1", t:{en:"dress", uk:"сукня"}},
  {w:"Kleidung", a:"die", l:"A1", t:{en:"clothing", uk:"одяг"}},
  {w:"Koffer", a:"der", l:"A1", t:{en:"suitcase", uk:"валіза"}},
  {w:"Kollege", a:"der", l:"A1", t:{en:"colleague", uk:"колега"}},
  {w:"Kontakt", a:"der", l:"A1", t:{en:"contact", uk:"контакт"}},
  {w:"Konto", a:"das", l:"A1", t:{en:"account", uk:"рахунок"}},
  {w:"Kopf", a:"der", l:"A1", t:{en:"head", uk:"голова"}},
  {w:"Körper", a:"der", l:"A1", t:{en:"body", uk:"тіло"}},
  {w:"Kosten", a:"die", l:"A1", t:{en:"costs", uk:"витрати"}},
  {w:"Küche", a:"die", l:"A1", t:{en:"kitchen", uk:"кухня"}},
  {w:"Kuchen", a:"der", l:"A1", t:{en:"cake", uk:"пиріг"}},
  {w:"Kühlschrank", a:"der", l:"A1", t:{en:"fridge", uk:"холодильник"}},
  {w:"Kultur", a:"die", l:"A1", t:{en:"culture", uk:"культура"}},
  {w:"Kunde", a:"der", l:"A1", t:{en:"customer", uk:"клієнт"}},
  {w:"Kurs", a:"der", l:"A1", t:{en:"course", uk:"курс"}},
  {w:"Laden", a:"der", l:"A1", t:{en:"shop", uk:"магазин"}},
  {w:"Lampe", a:"die", l:"A1", t:{en:"lamp", uk:"лампа"}},
  {w:"Land", a:"das", l:"A1", t:{en:"country", uk:"країна"}},
  {w:"Laptop", a:"der", l:"A1", t:{en:"laptop", uk:"ноутбук"}},
  {w:"Leben", a:"das", l:"A1", t:{en:"life", uk:"життя"}},
  {w:"Lehrer", a:"der", l:"A1", t:{en:"teacher", uk:"вчитель"}},
  {w:"Leute", a:"die", l:"A1", t:{en:"people", uk:"люди"}},
  {w:"Licht", a:"das", l:"A1", t:{en:"light", uk:"світло"}},
  {w:"Lied", a:"das", l:"A1", t:{en:"song", uk:"пісня"}},
  {w:"Liter", a:"der", l:"A1", t:{en:"liter", uk:"літр"}},
  {w:"Löffel", a:"der", l:"A1", t:{en:"spoon", uk:"ложка"}},
  {w:"Luft", a:"die", l:"A1", t:{en:"air", uk:"повітря"}},
  {w:"Lust", a:"die", l:"A1", t:{en:"pleasure", uk:"бажання"}},
  {w:"Mädchen", a:"das", l:"A1", t:{en:"girl", uk:"дівчинка"}},
  {w:"Magen", a:"der", l:"A1", t:{en:"stomach", uk:"шлунок"}},
  {w:"Mai", a:"der", l:"A1", t:{en:"May", uk:"травень"}},
  {w:"Mal", a:"das", l:"A1", t:{en:"time/occurrence", uk:"раз"}},
  {w:"Mann", a:"der", l:"A1", t:{en:"man", uk:"чоловік"}},
  {w:"Mantel", a:"der", l:"A1", t:{en:"coat", uk:"пальто"}},
  {w:"Markt", a:"der", l:"A1", t:{en:"market", uk:"ринок"}},
  {w:"März", a:"der", l:"A1", t:{en:"March", uk:"березень"}},
  {w:"Maschine", a:"die", l:"A1", t:{en:"machine", uk:"машина"}},
  {w:"Medikament", a:"das", l:"A1", t:{en:"medicine", uk:"ліки"}},
  {w:"Meer", a:"das", l:"A1", t:{en:"sea", uk:"море"}},
  {w:"Mensch", a:"der", l:"A1", t:{en:"person", uk:"людина"}},
  {w:"Messer", a:"das", l:"A1", t:{en:"knife", uk:"ніж"}},
  {w:"Miete", a:"die", l:"A1", t:{en:"rent", uk:"оренда"}},
  {w:"Minute", a:"die", l:"A1", t:{en:"minute", uk:"хвилина"}},
  {w:"Mittag", a:"der", l:"A1", t:{en:"noon", uk:"полудень"}},
  {w:"Mittwoch", a:"der", l:"A1", t:{en:"Wednesday", uk:"середа"}},
  {w:"Möbel", a:"die", l:"A1", t:{en:"furniture", uk:"меблі"}},
  {w:"Moment", a:"der", l:"A1", t:{en:"moment", uk:"момент"}},
  {w:"Monat", a:"der", l:"A1", t:{en:"month", uk:"місяць"}},
  {w:"Montag", a:"der", l:"A1", t:{en:"Monday", uk:"понеділок"}},
  {w:"Morgen", a:"der", l:"A1", t:{en:"morning", uk:"ранок"}},
  {w:"Mund", a:"der", l:"A1", t:{en:"mouth", uk:"рот"}},
  {w:"Museum", a:"das", l:"A1", t:{en:"museum", uk:"музей"}},
  {w:"Musik", a:"die", l:"A1", t:{en:"music", uk:"музика"}},
  {w:"Mutter", a:"die", l:"A1", t:{en:"mother", uk:"мати"}},
  {w:"Nachbar", a:"der", l:"A1", t:{en:"neighbor", uk:"сусід"}},
  {w:"Nachricht", a:"die", l:"A1", t:{en:"message", uk:"повідомлення"}},
  {w:"Nacht", a:"die", l:"A1", t:{en:"night", uk:"ніч"}},
  {w:"Name", a:"der", l:"A1", t:{en:"name", uk:"ім'я"}},
  {w:"Nase", a:"die", l:"A1", t:{en:"nose", uk:"ніс"}},
  {w:"Natur", a:"die", l:"A1", t:{en:"nature", uk:"природа"}},
  {w:"Nebel", a:"der", l:"A1", t:{en:"fog", uk:"туман"}},
  {w:"Norden", a:"der", l:"A1", t:{en:"north", uk:"північ"}},
  {w:"Notfall", a:"der", l:"A1", t:{en:"emergency", uk:"надзвичайний випадок"}},
  {w:"Nummer", a:"die", l:"A1", t:{en:"number", uk:"номер"}},
  {w:"Obst", a:"das", l:"A1", t:{en:"fruit", uk:"фрукти"}},
  {w:"Oktober", a:"der", l:"A1", t:{en:"October", uk:"жовтень"}},
  {w:"Onkel", a:"der", l:"A1", t:{en:"uncle", uk:"дядько"}},
  {w:"Opa", a:"der", l:"A1", t:{en:"grandpa", uk:"дідусь"}},
  {w:"Orange", a:"die", l:"A1", t:{en:"orange", uk:"апельсин"}},
  {w:"Ordnung", a:"die", l:"A1", t:{en:"order", uk:"порядок"}},
  {w:"Ort", a:"der", l:"A1", t:{en:"place", uk:"місце"}},
  {w:"Osten", a:"der", l:"A1", t:{en:"east", uk:"схід"}},
  {w:"Paket", a:"das", l:"A1", t:{en:"package", uk:"пакет"}},
  {w:"Papier", a:"das", l:"A1", t:{en:"paper", uk:"папір"}},
  {w:"Park", a:"der", l:"A1", t:{en:"park", uk:"парк"}},
  {w:"Party", a:"die", l:"A1", t:{en:"party", uk:"вечірка"}},
  {w:"Pass", a:"der", l:"A1", t:{en:"passport", uk:"паспорт"}},
  {w:"Pause", a:"die", l:"A1", t:{en:"break", uk:"пауза"}},
  {w:"Person", a:"die", l:"A1", t:{en:"person", uk:"особа"}},
  {w:"Pfand", a:"das", l:"A1", t:{en:"deposit", uk:"застава"}},
  {w:"Pfeffer", a:"der", l:"A1", t:{en:"pepper", uk:"перець"}},
  {w:"Pferd", a:"das", l:"A1", t:{en:"horse", uk:"кінь"}},
  {w:"Pflanze", a:"die", l:"A1", t:{en:"plant", uk:"рослина"}},
  {w:"Platz", a:"der", l:"A1", t:{en:"place/square", uk:"місце/площа"}},
  {w:"Polizei", a:"die", l:"A1", t:{en:"police", uk:"поліція"}},
  {w:"Portion", a:"die", l:"A1", t:{en:"portion", uk:"порція"}},
  {w:"Post", a:"die", l:"A1", t:{en:"post", uk:"пошта"}},
  {w:"Preis", a:"der", l:"A1", t:{en:"price", uk:"ціна"}},
  {w:"Problem", a:"das", l:"A1", t:{en:"problem", uk:"проблема"}},
  {w:"Produkt", a:"das", l:"A1", t:{en:"product", uk:"продукт"}},
  {w:"Programm", a:"das", l:"A1", t:{en:"program", uk:"програма"}},
  {w:"Projekt", a:"das", l:"A1", t:{en:"project", uk:"проект"}},
  {w:"Prüfung", a:"die", l:"A1", t:{en:"exam", uk:"іспит"}},
  {w:"Punkt", a:"der", l:"A1", t:{en:"point", uk:"пункт"}},
  {w:"Quittung", a:"die", l:"A1", t:{en:"receipt", uk:"квитанція"}},
  {w:"Radio", a:"das", l:"A1", t:{en:"radio", uk:"радіо"}},
  {w:"Rathaus", a:"das", l:"A1", t:{en:"city hall", uk:"ратуша"}},
  {w:"Rechnung", a:"die", l:"A1", t:{en:"bill", uk:"рахунок"}},
  {w:"Regen", a:"der", l:"A1", t:{en:"rain", uk:"дощ"}},
  {w:"Region", a:"die", l:"A1", t:{en:"region", uk:"регіон"}},
  {w:"Reis", a:"der", l:"A1", t:{en:"rice", uk:"рис"}},
  {w:"Reise", a:"die", l:"A1", t:{en:"travel", uk:"подорож"}},
  {w:"Rezept", a:"das", l:"A1", t:{en:"recipe", uk:"рецепт"}},
  {w:"Rock", a:"der", l:"A1", t:{en:"skirt", uk:"спідниця"}},
  {w:"Rücken", a:"der", l:"A1", t:{en:"back", uk:"спина"}},
  {w:"Saft", a:"der", l:"A1", t:{en:"juice", uk:"сік"}},
  {w:"Salat", a:"der", l:"A1", t:{en:"salad", uk:"салат"}},
  {w:"Salz", a:"das", l:"A1", t:{en:"salt", uk:"сіль"}},
  {w:"Samstag", a:"der", l:"A1", t:{en:"Saturday", uk:"субота"}},
  {w:"Satz", a:"der", l:"A1", t:{en:"sentence", uk:"речення"}},
  {w:"Schal", a:"der", l:"A1", t:{en:"scarf", uk:"шарф"}},
  {w:"Schiff", a:"das", l:"A1", t:{en:"ship", uk:"корабель"}},
  {w:"Schild", a:"das", l:"A1", t:{en:"sign", uk:"щит/вивіска"}},
  {w:"Schirm", a:"der", l:"A1", t:{en:"umbrella", uk:"парасоля"}},
  {w:"Schlaf", a:"der", l:"A1", t:{en:"sleep", uk:"сон"}},
  {w:"Schloss", a:"das", l:"A1", t:{en:"castle", uk:"замок"}},
  {w:"Schluss", a:"der", l:"A1", t:{en:"end", uk:"завершення"}},
  {w:"Schlüssel", a:"der", l:"A1", t:{en:"key", uk:"ключ"}},
  {w:"Schmerz", a:"der", l:"A1", t:{en:"pain", uk:"біль"}},
  {w:"Schokolade", a:"die", l:"A1", t:{en:"chocolate", uk:"шоколад"}},
  {w:"Schrank", a:"der", l:"A1", t:{en:"closet", uk:"шафа"}},
  {w:"Schuh", a:"der", l:"A1", t:{en:"shoe", uk:"взуття"}},
  {w:"Schule", a:"die", l:"A1", t:{en:"school", uk:"школа"}},
  {w:"Schüler", a:"der", l:"A1", t:{en:"student", uk:"учень"}},
  {w:"Schwester", a:"die", l:"A1", t:{en:"sister", uk:"сестра"}},
  {w:"See", a:"der", l:"A1", t:{en:"lake", uk:"озеро"}},
  {w:"Seite", a:"die", l:"A1", t:{en:"page", uk:"сторінка"}},
  {w:"Sekunde", a:"die", l:"A1", t:{en:"second", uk:"секунда"}},
  {w:"September", a:"der", l:"A1", t:{en:"September", uk:"вересень"}},
  {w:"Service", a:"der", l:"A1", t:{en:"service", uk:"сервіс"}},
  {w:"Sessel", a:"der", l:"A1", t:{en:"armchair", uk:"крісло"}},
  {w:"Sofa", a:"das", l:"A1", t:{en:"sofa", uk:"диван"}},
  {w:"Sohn", a:"der", l:"A1", t:{en:"son", uk:"син"}},
  {w:"Sommer", a:"der", l:"A1", t:{en:"summer", uk:"літо"}},
  {w:"Sonne", a:"die", l:"A1", t:{en:"sun", uk:"сонце"}},
  {w:"Sonntag", a:"der", l:"A1", t:{en:"Sunday", uk:"неділя"}},
  {w:"Soße", a:"die", l:"A1", t:{en:"sauce", uk:"соус"}},
  {w:"Spaß", a:"der", l:"A1", t:{en:"fun", uk:"задоволення"}},
  {w:"Spiel", a:"das", l:"A1", t:{en:"game", uk:"гра"}},
  {w:"Sport", a:"der", l:"A1", t:{en:"sport", uk:"спорт"}},
  {w:"Sprache", a:"die", l:"A1", t:{en:"language", uk:"мова"}},
  {w:"Stadt", a:"die", l:"A1", t:{en:"city", uk:"місто"}},
  {w:"Station", a:"die", l:"A1", t:{en:"station", uk:"станція"}},
  {w:"Stau", a:"der", l:"A1", t:{en:"traffic jam", uk:"затор"}},
  {w:"Stelle", a:"die", l:"A1", t:{en:"position", uk:"місце/посада"}},
  {w:"Steuer", a:"die", l:"A1", t:{en:"tax", uk:"податок"}},
  {w:"Stift", a:"der", l:"A1", t:{en:"pen", uk:"олівець/ручка"}},
  {w:"Stock", a:"der", l:"A1", t:{en:"floor", uk:"поверх"}},
  {w:"Straße", a:"die", l:"A1", t:{en:"street", uk:"вулиця"}},
  {w:"Strom", a:"der", l:"A1", t:{en:"electricity", uk:"струм"}},
  {w:"Stück", a:"das", l:"A1", t:{en:"piece", uk:"шматок"}},
  {w:"Student", a:"der", l:"A1", t:{en:"student", uk:"студент"}},
  {w:"Studium", a:"das", l:"A1", t:{en:"study", uk:"навчання"}},
  {w:"Stuhl", a:"der", l:"A1", t:{en:"chair", uk:"стілець"}},
  {w:"Stunde", a:"die", l:"A1", t:{en:"hour", uk:"година"}},
  {w:"Süden", a:"der", l:"A1", t:{en:"south", uk:"південь"}},
  {w:"Supermarkt", a:"der", l:"A1", t:{en:"supermarket", uk:"супермаркет"}},
  {w:"Suppe", a:"die", l:"A1", t:{en:"soup", uk:"суп"}},
  {w:"Tag", a:"der", l:"A1", t:{en:"day", uk:"день"}},
  {w:"Tankstelle", a:"die", l:"A1", t:{en:"gas station", uk:"бензоколонка"}},
  {w:"Tante", a:"die", l:"A1", t:{en:"aunt", uk:"тітка"}},
  {w:"Tasche", a:"die", l:"A1", t:{en:"bag", uk:"сумка"}},
  {w:"Tasse", a:"die", l:"A1", t:{en:"cup", uk:"чашка"}},
  {w:"Taxi", a:"das", l:"A1", t:{en:"taxi", uk:"таксі"}},
  {w:"Tee", a:"der", l:"A1", t:{en:"tea", uk:"чай"}},
  {w:"Teil", a:"der/das", l:"A1", t:{en:"part", uk:"частина"}},
  {w:"Telefon", a:"das", l:"A1", t:{en:"telephone", uk:"телефон"}},
  {w:"Teller", a:"der", l:"A1", t:{en:"plate", uk:"тарілка"}},
  {w:"Teppich", a:"der", l:"A1", t:{en:"carpet", uk:"килим"}},
  {w:"Termin", a:"der", l:"A1", t:{en:"appointment", uk:"термін/зустріч"}},
  {w:"Text", a:"der", l:"A1", t:{en:"text", uk:"текст"}},
  {w:"Thema", a:"das", l:"A1", t:{en:"topic", uk:"тема"}},
  {w:"Ticket", a:"das", l:"A1", t:{en:"ticket", uk:"квиток"}},
  {w:"Tier", a:"das", l:"A1", t:{en:"animal", uk:"тварина"}},
  {w:"Tisch", a:"der", l:"A1", t:{en:"table", uk:"стіл"}},
  {w:"Tochter", a:"die", l:"A1", t:{en:"daughter", uk:"донька"}},
  {w:"Toilette", a:"die", l:"A1", t:{en:"toilet", uk:"туалет"}},
  {w:"Tomate", a:"die", l:"A1", t:{en:"tomate", uk:"помідор"}},
  {w:"Topf", a:"der", l:"A1", t:{en:"pot", uk:"каструля"}},
  {w:"Tourist", a:"der", l:"A1", t:{en:"tourist", uk:"турист"}},
  {w:"Training", a:"das", l:"A1", t:{en:"training", uk:"тренування"}},
  {w:"Transport", a:"der", l:"A1", t:{en:"transport", uk:"транспорт"}},
  {w:"Treppe", a:"die", l:"A1", t:{en:"stairs", uk:"сходи"}},
  {w:"Trinkgeld", a:"das", l:"A1", t:{en:"tip", uk:"чайові"}},
  {w:"Unfall", a:"der", l:"A1", t:{en:"accident", uk:"аварія"}},
  {w:"Universität", a:"die", l:"A1", t:{en:"university", uk:"університет"}},
  {w:"Unterricht", a:"der", l:"A1", t:{en:"lesson", uk:"заняття"}},
  {w:"Urlaub", a:"der", l:"A1", t:{en:"vacation", uk:"відпустка"}},
  {w:"Vater", a:"der", l:"A1", t:{en:"father", uk:"батько"}},
  {w:"Verbot", a:"das", l:"A1", t:{en:"prohibition", uk:"заборона"}},
  {w:"Verein", a:"der", l:"A1", t:{en:"association", uk:"клуб/спілка"}},
  {w:"Verkehr", a:"der", l:"A1", t:{en:"traffic", uk:"рух"}},
  {w:"Vermieter", a:"der", l:"A1", t:{en:"landlord", uk:"орендодавець"}},
  {w:"Verspätung", a:"die", l:"A1", t:{en:"delay", uk:"запізнення"}},
  {w:"Vertrag", a:"der", l:"A1", t:{en:"contract", uk:"контракт"}},
  {w:"Viertel", a:"das", l:"A1", t:{en:"quarter", uk:"чверть"}},
  {w:"Vogel", a:"der", l:"A1", t:{en:"bird", uk:"птах"}},
  {w:"Vorname", a:"der", l:"A1", t:{en:"first name", uk:"ім'я"}},
  {w:"Vormittag", a:"der", l:"A1", t:{en:"late morning", uk:"дополудня"}},
  {w:"Wagen", a:"der", l:"A1", t:{en:"car/wagon", uk:"автомобіль"}},
  {w:"Wald", a:"der", l:"A1", t:{en:"forest", uk:"ліс"}},
  {w:"Wand", a:"die", l:"A1", t:{en:"wall", uk:"стіна"}},
  {w:"Wasser", a:"das", l:"A1", t:{en:"water", uk:"вода"}},
  {w:"Weg", a:"der", l:"A1", t:{en:"way", uk:"шлях"}},
  {w:"Wein", a:"der", l:"A1", t:{en:"wine", uk:"вино"}},
  {w:"Welt", a:"die", l:"A1", t:{en:"world", uk:"світ"}},
  {w:"Werkstatt", a:"die", l:"A1", t:{en:"workshop", uk:"майстерня"}},
  {w:"Wetter", a:"das", l:"A1", t:{en:"weather", uk:"погода"}},
  {w:"Wind", a:"der", l:"A1", t:{en:"wind", uk:"вітер"}},
  {w:"Winter", a:"der", l:"A1", t:{en:"winter", uk:"зима"}},
  {w:"Woche", a:"die", l:"A1", t:{en:"week", uk:"тиждень"}},
  {w:"Wochenende", a:"das", l:"A1", t:{en:"weekend", uk:"вихідні"}},
  {w:"Wohnung", a:"die", l:"A1", t:{en:"apartment", uk:"квартира"}},
  {w:"Wolke", a:"die", l:"A1", t:{en:"cloud", uk:"хмара"}},
  {w:"Wort", a:"das", l:"A1", t:{en:"word", uk:"слово"}},
  {w:"Wunsch", a:"der", l:"A1", t:{en:"wish", uk:"бажання"}},
  {w:"Wurst", a:"die", l:"A1", t:{en:"sausage", uk:"ковбаса"}},
  {w:"Zahl", a:"die", l:"A1", t:{en:"number", uk:"число"}},
  {w:"Zahn", a:"der", l:"A1", t:{en:"tooth", uk:"зуб"}},
  {w:"Zeit", a:"die", l:"A1", t:{en:"time", uk:"час"}},
  {w:"Zeitschrift", a:"die", l:"A1", t:{en:"magazine", uk:"журнал"}},
  {w:"Zeitung", a:"die", l:"A1", t:{en:"newspaper", uk:"газета"}},
  {w:"Zentrum", a:"das", l:"A1", t:{en:"center", uk:"центр"}},
  {w:"Zettel", a:"der", l:"A1", t:{en:"note", uk:"записка"}},
  {w:"Zeugnis", a:"das", l:"A1", t:{en:"certificate", uk:"свідоцтво/атестат"}},
  {w:"Ziel", a:"das", l:"A1", t:{en:"goal", uk:"ціль"}},
  {w:"Zimmer", a:"das", l:"A1", t:{en:"room", uk:"кімната"}},
  {w:"Zoo", a:"der", l:"A1", t:{en:"zoo", uk:"зоопарк"}},
  {w:"Zucker", a:"der", l:"A1", t:{en:"sugar", uk:"цукор"}},
  {w:"Zug", a:"der", l:"A1", t:{en:"train", uk:"поїзд"}},
  {w:"Zukunft", a:"die", l:"A1", t:{en:"future", uk:"майбутнє"}}
];
